<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
/**
 * @var \Magento\Backend\Block\Template $block
 */
?>
<?php
/** @var \MageWorx\DeliveryDate\Block\Adminhtml\Queue\Calendar $parentBlock */
$parentBlock = $block->getParentBlock();
?>
<?php if ($parentBlock->getUseMenu()): ?>
    <div id="menu">
        <?php if ($block->getUseCalendarType()): ?>
            <span class="dropdown">
                <button id="dropdownMenu-calendarType" class="btn btn-default btn-sm dropdown-toggle" type="button"
                        data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="true">
                    <i id="calendarTypeIcon" class="calendar-icon ic_view_month" style="margin-right: 4px;"></i>
                    <span id="calendarTypeName"><?= $block->escapeHtml(__('Dropdown')); ?></span>&nbsp;
                    <i class="calendar-icon tui-full-calendar-dropdown-arrow"></i>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu-calendarType">
                    <li role="presentation">
                        <a class="dropdown-menu-title" role="menuitem" data-action="toggle-daily">
                            <i class="calendar-icon ic_view_day"></i>
                            <?= $block->escapeHtml(__('Daily')); ?>
                        </a>
                    </li>
                    <li role="presentation">
                        <a class="dropdown-menu-title" role="menuitem" data-action="toggle-weekly">
                            <i class="calendar-icon ic_view_week"></i><?= $block->escapeHtml(__('Weekly')); ?>
                        </a>
                    </li>
                    <li role="presentation">
                        <a class="dropdown-menu-title" role="menuitem" data-action="toggle-monthly">
                            <i class="calendar-icon ic_view_month"></i><?= $block->escapeHtml(__('Month')); ?>
                        </a>
                    </li>
                    <li role="presentation">
                        <a class="dropdown-menu-title" role="menuitem" data-action="toggle-weeks2">
                            <i class="calendar-icon ic_view_week"></i><?= $block->escapeHtml(__('2 weeks')); ?>
                        </a>
                    </li>
                    <li role="presentation">
                        <a class="dropdown-menu-title" role="menuitem" data-action="toggle-weeks3">
                            <i class="calendar-icon ic_view_week"></i><?= $block->escapeHtml(__('3 weeks')); ?>
                        </a>
                    </li>
                    <li role="presentation" class="dropdown-divider"></li>
                    <li role="presentation">
                        <a role="menuitem" data-action="toggle-workweek">
                            <input type="checkbox" class="tui-full-calendar-checkbox-square" value="toggle-workweek"
                                   checked>
                            <span class="checkbox-title"></span><?= $block->escapeHtml(__('Show weekends')); ?>
                        </a>
                    </li>
                </ul>
            </span>
        <?php endif; ?>
        <span id="menu-navi">
            <button type="button" class="btn btn-default btn-sm move-today"
                    data-action="move-today"><?= $block->escapeHtml(__('Today')); ?></button>
            <button type="button" class="btn btn-default btn-sm move-day" data-action="move-prev">
                <i class="calendar-icon ic-arrow-line-left" data-action="move-prev"></i>
            </button>
            <button type="button" class="btn btn-default btn-sm move-day" data-action="move-next">
                <i class="calendar-icon ic-arrow-line-right" data-action="move-next"></i>
            </button>
        </span>
        <span id="renderRange" class="render-range"></span>
    </div>
<?php endif; ?>