<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\Model\ViewModelRegistry;
use Magewirephp\Magewire\ViewModel\Magewire;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$magewireScripts = $viewModels->require(Magewire::class);
$messageFourZeroFour = 'Something went wrong. Please refresh the page and try again.';
?>
<script>
    'use strict';

    (() => {
        const magewireOriginOnErrorCallback = Magewire.components.onErrorCallback;

        Magewire.onError((status, response) => {
            magewireOriginOnErrorCallback(status, response)

            if (status === 404) {
                if (confirm(`${ status }: <?= $escaper->escapeJs(__($messageFourZeroFour)) ?>`)) {
                    window.location.reload()
                }

                return false
            }

            <?php if ($magewireScripts->isProductionMode()): ?>
            response.clone().text().then((result) => {
                result = JSON.parse(result)
                window.dispatchMessages([{type: 'error', text: result.message || 'Something went wrong'}])
            }).catch((exception) => {
                console.error(exception)
            })
            <?php endif ?>
        })
    })()
</script>
