<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Hyva\Theme\Model\ViewModelRegistry;

/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$basePriceModel = $block->getPriceType('base_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
/** @var \Magento\Framework\Pricing\Helper\Data $priceHelper */
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');

/** @var ViewModelRegistry $viewModels */

$compareViewModel = $viewModels->require(\Actuate\ReliantDirectTheme\ViewModel\CommonViewModel::class);
?>
<?php if ($block->isProductList()): ?>
    <span class="normal-price mr-3">
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label' => __('As low as'),
            'price_id' => $block->getPriceId('product-price-' . $idSuffix),
            'price_type' => 'finalPrice',
            'include_container' => true,
            'schema' => $schema,
        ]);
        ?>
    </span>
    <?php if ($block->hasSpecialPrice()): ?>
        <?php if ($priceModel->getAmount()->getValue() !== $finalPriceModel->getAmount()->getValue()): ?>
            <span class="old-price sly-old-price no-display">
                <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                    'display_label'     => __(''),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
            <div class="price-container">
                <span class="save-upto-excl-price text-[#D30202] text-lg leading-6 font-bold font-serif">
                    Save <span class="save-price !text-lg">
                        <?= $priceHelper->currency(
                            $priceModel->getAmount()->getValue() - $finalPriceModel->getAmount()->getValue(),
                            true,
                            false
                        ); ?></span>
                </span>
            </div>
        <?php endif;?>
    <?php endif;?>
<?php endif;?>
<span class="normal-price<?= $block->isProductList() ? ' w-full' : ''?>">
    <?php if ($block->isProductList()): ?>
        <span class="normal-incl-vat flex font-semibold items-baseline text-base font-serif">
            (<span class="price-container price-final_price tax weee">
                <span class="price-label"></span>
                <span id="product-price-<?= $block->getSaleableItem()->getId()?>" data-price-amount="<?= $finalPriceModel->getAmount()->getValue()?>" data-price-type="finalPrice" class="price-wrapper ">
                <span class="price"><?= /** @noEscape */ str_replace('.00', '', $compareViewModel->convertPriceWithPrecision(($finalPriceModel->getAmount()->getValue()/1.2), 2)) ?></span></span>
            </span>&nbsp;ex VAT)
        </span>
    <?php else: ?>
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label' => $block->isProductList() ? __('') : __('As low as'),
            'price_id' => $block->getPriceId('product-price-' . $idSuffix),
            'price_type' => 'finalPrice',
            'include_container' => true,
            'schema' => $schema,
        ]);
        ?>
    <?php endif;?>
</span>

<?php if (!$block->isProductList() && $block->hasSpecialPrice()) : ?>
    <span class="old-price sly-old-price no-display">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php endif; ?>

<?php if ($block->showMinimalPrice()) : ?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else :?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
