<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Customer $customer */
$customer = $viewModels->require(Customer::class);
/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
$awesomeicons6Brands = $viewModels->require(\Jajuma\AwesomeHyva\ViewModel\Awesomeicons6Brands::class);
?>
<div class="w-full flex flex-wrap">
    <div class="w-full grid grid-cols-2 gap-x-8 md:grid-cols-4">
        <div class="mb-4">
            <h4 class="text-base font-semibold text-black mb-2.5"><?= $escaper->escapeHtml(__('Visit Us')) ?></h4>
            <ul>
                <li class="w-full text-sm mb-2 text-gray-900"><a href="/contact" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Visit Blackpool Showroom')) ?>"><?= $escaper->escapeHtml(__('Visit Blackpool Showroom')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/contact" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Visit Thornton Cleveleys Showroom')) ?>"><?= $escaper->escapeHtml(__('Visit Thornton Cleveleys Showroom')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/contact" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Contact Us')) ?>"><?= $escaper->escapeHtml(__('Contact Us')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="tel:+443300577142" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Tel: 0330 057 7142')) ?>"><?= $escaper->escapeHtml(__('Tel: 0330 057 7142')) ?></a></li>
            </ul>
        </div>
        <div class="mb-4">
            <h4 class="text-base font-semibold text-black mb-2"><?= $escaper->escapeHtml(__('Our Services')) ?></h4>
            <ul>
                <li class="w-full text-sm text-gray-900"><a href="/customer/account" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Your Account')) ?>"><?= $escaper->escapeHtml(__('Your Account')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/delivery-information" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Delivery Information')) ?>"><?= $escaper->escapeHtml(__('Delivery Information')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/returns" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Refund &amp; Returns Policy')) ?>"><?= $escaper->escapeHtml(__('Refund &amp; Returns Policy')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/price-match" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Price Match Guarantee')) ?>"><?= $escaper->escapeHtml(__('Price Match Guarantee')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/finance-options" class="block py-1 text-gray-900 hover:text-[#000d40]" title="<?= $escaper->escapeHtml(__('Finance Options')) ?>"><?= $escaper->escapeHtml(__('Finance Options')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/services" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Installation Services')) ?>"><?= $escaper->escapeHtml(__('Installation Services')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/affiliates" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Affiliates')) ?>"><?= $escaper->escapeHtml(__('Affiliates')) ?></a></li>
            </ul>
        </div>
        <div class="mb-4">
            <h4 class="text-base font-semibold text-black mb-2"><?= $escaper->escapeHtml(__('Company Information')) ?></h4>
            <ul>
                <li class="w-full text-sm text-gray-900"><a href="/about-us" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('About Us')) ?>"><?= $escaper->escapeHtml(__('About Us')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/faqs" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__("FAQ's")) ?>"><?= $escaper->escapeHtml(__("FAQ's")) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="https://www.reliant.co.uk/reliant-reviews" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__("Customer Reviews")) ?>" target="_blank"><?= $escaper->escapeHtml(__("Customer Reviews")) ?></a></li>

                <li class="w-full text-sm text-gray-900"><a href="/blog" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Tech Guides')) ?>"><?= $escaper->escapeHtml(__('Tech Guides')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/privacy-policy" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Cookies Policy')) ?>"><?= $escaper->escapeHtml(__('Cookies Policy')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/terms-and-conditions" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Terms & Conditions')) ?>"><?= $escaper->escapeHtml(__('Terms & Conditions')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/trade-sales" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Trade Sales')) ?>"><?= $escaper->escapeHtml(__('Trade Sales')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/weee-recycling" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('WEEE/Recycling')) ?>"><?= $escaper->escapeHtml(__('WEEE/Recycling')) ?></a></li>
            </ul>
        </div>
        <div class="mb-4">
            <h4 class="text-base font-semibold text-black mb-2"><?= $escaper->escapeHtml(__('Useful Links')) ?></h4>
            <ul>
                <li class="w-full text-sm text-gray-900"><a href="/televisions/4k-ultra-hd-tvs" class="text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('4K TVs')) ?>"><?= $escaper->escapeHtml(__('4K TVs')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/televisions/8k-tvs" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('8K TVs')) ?>"><?= $escaper->escapeHtml(__('8K TVs')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/televisions" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Smart TVs')) ?>"><?= $escaper->escapeHtml(__('Smart TVs')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/best-tv-deals" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Latest Deals')) ?>"><?= $escaper->escapeHtml(__('Best TV Deals')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/tvs-for-gamers" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Best Gaming TVs')) ?>"><?= $escaper->escapeHtml(__('Best Gaming TVs')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/discount-codes" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Discount Codes')) ?>"><?= $escaper->escapeHtml(__('Discount Codes')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/55-to-64-inch" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Best Gaming TVs')) ?>"><?= $escaper->escapeHtml(__('55 Inch TV')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/65-to-74-inch" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Quooker Taps')) ?>"><?= $escaper->escapeHtml(__('65 Inch TV')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/75-to-98-inch" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Ambilight TV')) ?>"><?= $escaper->escapeHtml(__('75 Inch TV')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/brands" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Shop by Brand')) ?>"><?= $escaper->escapeHtml(__('Shop by Brand')) ?></a></li>
                <li class="w-full text-sm text-gray-900"><a href="/boxing-day-promise" class="block py-1 text-gray-900 hover:text-[#126366]" title="<?= $escaper->escapeHtml(__('Boxing Day Sale Promise')) ?>"><?= $escaper->escapeHtml(__('Boxing Day Sale Promise')) ?></a></li>
            </ul>
        </div>
    </div>
    <div class="w-full grid grid-cols-1 gap-8 md:grid-cols-4">
        <div class="hidden md:block">&nbsp;</div>
        <div class="border-t border-gray-300 border-solid pt-4 lg:mr-5">
            <h4 class="text-base font-semibold text-black mb-2.5"><?= $escaper->escapeHtml(__('Our Customers Love Us')) ?></h4>
            <!-- TrustBox widget - Mini -->
            <div class="trustpilot-widget" data-locale="en-GB" data-template-id="53aa8807dec7e10d38f59f32" data-businessunit-id="63c539f09322c7323cf3a390" data-style-height="150px" data-style-width="100%" data-theme="light">
                <a href="https://uk.trustpilot.com/review/reliant.co.uk" target="_blank" rel="noopener">Trustpilot</a>
            </div>
            <!-- End TrustBox widget -->
        </div>
        <div class="border-t border-gray-300 border-solid pt-4 lg:mr-5">
            <h4 class="text-base font-semibold text-black mb-2.5"><?= $escaper->escapeHtml(__('Ways To Pay')) ?></h4>
            <ul class="flex items-center">
                <li class="inline-block mr-2"><img src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/visa.png')) ?>" loading="lazy" alt="Pay with Visa" width="46" height="16"></li>
                <li class="inline-block mr-2"><img src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/mastercard.png')) ?>" loading="lazy" alt="Pay with Mastercard" width="27" height="21"></li>
                <li class="inline-block mr-2"><img src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/amex.png')) ?>" loading="lazy" alt="Pay with American Express" width="26" height="21"></li>
                <li class="inline-block mr-2"><img src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/paypal.png')) ?>" loading="lazy" alt="Pay with PayPal" width="56" height="16"></li>
                <li class="inline-block mr-2"><img src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/apple-pay.png')) ?>" loading="lazy" alt="Pay with ApplyPay" width="33" height="21"></li>
                <li class="inline-block mr-2"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" class="h-5 mx-auto"><path fill="#FFB300" d="M39.6,39c-4.2,3.1-10.5,5-15.6,5c-7.3,0-13.8-2.9-18.8-7.4c-0.4-0.4,0-0.8,0.4-0.6c5.4,3.1,11.5,4.9,18.3,4.9c4.6,0,10.4-1,15.1-3C39.7,37.7,40.3,38.5,39.6,39z M41.1,36.9c-0.5-0.7-3.5-0.3-4.8-0.2c-0.4,0-0.5-0.3-0.1-0.6c2.3-1.7,6.2-1.2,6.6-0.6c0.4,0.6-0.1,4.5-2.3,6.3c-0.3,0.3-0.7,0.1-0.5-0.2C40.5,40.4,41.6,37.6,41.1,36.9z"/><path fill="#37474F" d="M36.9,29.8c-1-1.3-2-2.4-2-4.9v-8.3c0-3.5,0-6.6-2.5-9c-2-1.9-5.3-2.6-7.9-2.6C19,5,14.2,7.2,13,13.4c-0.1,0.7,0.4,1,0.8,1.1l5.1,0.6c0.5,0,0.8-0.5,0.9-1c0.4-2.1,2.1-3.1,4.1-3.1c1.1,0,3.2,0.6,3.2,3v3c-3.2,0-6.6,0-9.4,1.2c-3.3,1.4-5.6,4.3-5.6,8.6c0,5.5,3.4,8.2,7.8,8.2c3.7,0,5.9-0.9,8.8-3.8c0.9,1.4,1.3,2.2,3,3.7c0.4,0.2,0.9,0.2,1.2-0.1l0,0c1-0.9,2.9-2.6,4-3.5C37.4,30.9,37.3,30.3,36.9,29.8z M27,22.1L27,22.1c0,2-0.1,6.9-5,6.9c-3,0-3-3-3-3c0-4.5,4.2-5,8-5V22.1z"/></li>
                <li class="inline-block">
                    <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet" width="106" height="36" viewBox="0 0 106 36" class="w-[70px]">
                        <path class="afterpay-logo-badge-background" fill="#b2fce4" d="m87.9659,35.9683l-69.9317,0a17.9342,17.9342 0 1 1 0,-35.8683l69.9317,0a17.9342,17.9342 0 1 1 0,35.8683z"></path>
                        <g class="afterpay-logo-badge-lockup">
                            <path d="m75.7442,13.8827l-5.2852,10.9026l-2.1897,0l1.9746,-4.073l-3.102,-6.8296l2.2483,0l1.9942,4.5748l2.1765,-4.5748l2.1832,0l0.0001,0z"></path>
                            <path d="m55.6334,17.7537a2.1505,2.1505 0 0 0 -2.105,-2.2157c-1.1599,0 -2.1048,0.932 -2.1048,2.2157c0,1.2708 0.9449,2.2157 2.1049,2.2157a2.1505,2.1505 0 0 0 2.105,-2.2157m-6.1324,7.0316l0,-10.9025l1.903,0l0,1.0035a3.076,3.076 0 0 1 2.4437,-1.147c2.0919,0 3.7341,1.7205 3.7341,3.9949s-1.6748,4.0078 -3.7797,4.0078a2.9977,2.9977 0 0 1 -2.3395,-1.0362l0,4.073l-1.9617,0l0,0.0065l0.0001,0z"></path>
                            <path d="m64.4506,17.7537c0,-1.3033 -0.945,-2.2157 -2.105,-2.2157c-1.1599,0 -2.1048,0.932 -2.1048,2.2157c0,1.2708 0.9449,2.2157 2.1049,2.2157c1.16,0 2.105,-0.9188 2.105,-2.2157m0.013,3.871l0,-1.0037a3.102,3.102 0 0 1 -2.4439,1.1274c-2.1244,0 -3.734,-1.7009 -3.734,-3.9948c0,-2.2743 1.6747,-4.0078 3.7797,-4.0078c0.9905,0 1.8247,0.4366 2.3981,1.1144l0,-0.9775l1.903,0l0,7.7419l-1.903,0l0.0001,0.0001z"></path>
                            <path d="m46.0668,14.6387s0.4822,-0.8993 1.6748,-0.8993c0.5083,0 0.8341,0.176 0.8341,0.176l0,1.9745s-0.7168,-0.4431 -1.375,-0.3519s-1.0753,0.6908 -1.0753,1.4989l0,4.5878l-1.968,0l0,-7.742l1.9029,0l0,0.756l0.0065,0z"></path>
                            <path d="m90.5242,13.4461l-2.2548,-1.2903l-2.2874,-1.3099a2.2744,2.2744 0 0 0 -3.4017,1.9681l0,0.2933c0,0.1629 0.0847,0.3128 0.228,0.391l1.0623,0.606a0.4431,0.4431 0 0 0 0.6582,-0.3845l0,-0.6973c0,-0.3454 0.3714,-0.5604 0.6712,-0.391l2.0854,1.1991l2.0788,1.1926a0.4497,0.4497 0 0 1 0,0.7755l-2.0788,1.1926l-2.0854,1.199a0.4497,0.4497 0 0 1 -0.6712,-0.391l0,-0.3454c0,-1.7464 -1.8899,-2.8413 -3.4018,-1.968l-2.2874,1.3098l-2.2548,1.2904a2.2809,2.2809 0 0 0 0,3.9426l2.2548,1.2903l2.2874,1.31a2.2744,2.2744 0 0 0 3.4018,-1.9682l0,-0.2932c0,-0.163 -0.0847,-0.3128 -0.2281,-0.391l-1.0622,-0.606a0.4431,0.4431 0 0 0 -0.6582,0.3844l0,0.6973c0,0.3454 -0.3715,0.5604 -0.6713,0.391l-2.0853,-1.199l-2.0789,-1.1927a0.4497,0.4497 0 0 1 0,-0.7755l2.0789,-1.1925l2.0853,-1.1991a0.4497,0.4497 0 0 1 0.6713,0.391l0,0.3454c0,1.7465 1.8898,2.8413 3.4017,1.968l2.2874,-1.3098l2.2548,-1.2903a2.2809,2.2809 0 0 0 0,-3.9427z"></path>
                            <path d="m22.2806,18.7377a3.8905,3.8905 0 0 1 -3.9296,3.0043a3.91,3.91 0 0 1 -4.0078,-3.9948a3.9492,3.9492 0 0 1 4.0404,-4.0078a3.897,3.897 0 0 1 3.884,2.9716l-2.0137,0a2.105,2.105 0 0 0 -1.8573,-1.16a2.1375,2.1375 0 0 0 -2.105,2.1962a2.1375,2.1375 0 0 0 2.105,2.1961c0.8211,0 1.5314,-0.4627 1.8703,-1.2056l2.0137,0z"></path>
                            <path d="m23.1864,21.6181l0,-10.922l1.9485,0l0,10.922l-1.9485,0z"></path>
                            <path d="m28.0675,18.262a1.9224,1.9224 0 0 0 1.9941,1.7921c0.8211,0 1.4532,-0.3845 1.8247,-1.0036l1.9941,0c-0.4627,1.6423 -1.9355,2.6915 -3.871,2.6915c-2.3395,0 -3.9752,-1.6423 -3.9752,-3.9753s1.7335,-4.0208 4.0209,-4.0208a3.871,3.871 0 0 1 3.9296,4.5161l-5.9172,0zm3.884,-1.2121c-0.1369,-1.0036 -0.958,-1.6096 -1.916,-1.6096s-1.7464,0.5865 -1.9485,1.6096l3.8645,0z"></path>
                            <path d="m40.9902,21.6181l0,-1.0035a3.089,3.089 0 0 1 -2.4438,1.1274c-2.118,0 -3.7276,-1.701 -3.7276,-3.9948c0,-2.2744 1.6683,-4.0078 3.7733,-4.0078c0.9905,0 1.8247,0.43 2.3981,1.1144l0,-0.9776l1.903,0l0,7.7354l-1.903,0l0,0.0066l0,-0.0001zm-0.0195,-3.8709c0,-1.2967 -0.945,-2.2156 -2.105,-2.2156c-1.16,0 -2.1049,0.9254 -2.1049,2.2157c0,1.2708 0.945,2.2157 2.105,2.2157c1.16,0 2.1049,-0.9124 2.1049,-2.2157l0,-0.0001z"></path>
                        </g>
                    </svg>
                </li>
            </ul>
        </div>
    </div>
</div>