<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityFormInterface;
use Hyva\Checkout\Magewire\Checkout\AddressView\MagewireAddressFormInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Directory\Model\Country as CountryModel;
use Magento\Directory\Model\Region as RegionModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use ReliantDirect\Checkout\ViewModel\Checkout;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var MagewireAddressFormInterface $magewire */
/** @var CountryModel $country */
/** @var RegionModel $region */
/** @var Escaper $escaper */
/** @var EntityFormInterface $form */

$iconsViewModel = $viewModels->require(HeroiconsOutline::class);
$form = $magewire->getPublicForm();
$namespace = $form->getNamespace();

/** @var Checkout $actuateCheckoutViewModel */
$actuateCheckoutViewModel = $viewModels->require(Checkout::class);
$formAttribute = $form->getAttributes() ?? [];
$id = $formAttribute['id'] ?? uniqid();
?>
<div>
    <header class="section-title border-b border-gray-400 pb-1 mb-6">
        <h2 class="text-gray-800 text-xl font-medium">
            <?= $escaper->escapeHtml(__('New Address')) ?>
        </h2>
    </header>

    <form <?= /* @noEscape */ $form->renderAttributes($escaper) ?>
          class="space-y-2 address-form"
          x-data="hyva.formValidation($el)"
          novalidate
    >
        <div class="grid grid-cols-12 gap-x-4">
            <?= /** @noEscape */ $block->getChildHtml('address-form.before') ?>

            <?php if ($form->hasFields()): ?>
                <?php foreach ($form->getFields() as $field): ?>
                    <?php if ($field->canRender()): ?>
                        <?php /** @purge: md:col-span-3 md:col-span-6 md:col-span-9 md:col-span-12 */ ?>
                        <div class="<?= $escaper->escapeHtmlAttr($field->renderWrapperClass(['col-span-12'])) ?>"
                             <?= /* @noEscape */ $field->renderAttributes($escaper, 'wrapper') ?>
                        >
                            <?= /* @noEscape */ $field->render() ?>

                            <?php if ($magewire->hasError($field->getId())): ?>
                                <?= /** @noEscape */ $magewire->getError($field->getId()) ?>
                            <?php endif ?>

                            <?php if ($actuateCheckoutViewModel->isUkPostCodeLookUpEnabled()): ?>
                            <?php if ($field->getName() == 'postcode'): ?>
                                <div id="crafty_postcode_result_<?= $id;?>" class="lookup-result"></div>
                                <button type="button" id="lookup-address-<?= $id;?>" class="lookup-btn btn btn-primary mt-5 px-[25px] max767:py-1.5 pt-3 max767:mb-7">
                                    <?= __('Lookup Address');?>
                                </button>
                            <?php endif; ?>
                        <?php endif; ?>
                        </div>
                    <?php endif ?>
                <?php endforeach ?>
            <?php endif ?>

            <?= /** @noEscape */ $block->getChildHtml('address-form.after') ?>
        </div>

        <div class="flex space-x-4 items-center">
            <button type="button"
                    class="btn btn-primary"
                    x-on:click="validate().then(() => $wire.submit()).catch(() => {})"
                    wire:loading.attr="disabled"
            >
                <?= $escaper->escapeHtml(__('Save')) ?>
            </button>

            <button type="button"
                    class="btn btn-secondary"
                    x-on:click="window.hyva.modal.pop()"
            >
                <?= $escaper->escapeHtml(__('Cancel')) ?>
            </button>
        </div>
    </form>
</div>
