<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<script>
    function initCheckoutLoader(options = {}) {
        return {
            active: false,

            options: Object.assign({
                startEvent: 'checkout:loader:start',
                stopEvent: 'checkout:loader:stop'
            }, options),

            overlay() {
                window.addEventListener(this.options.startEvent, () => this.active = true)
                window.addEventListener(this.options.stopEvent, () => this.active = false)

                return {
                    ['x-show']() {
                        return this.active
                    }
                }
            }
        }
    }
</script>

<?= $this->getChildHtml('after') ?>
