<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display subtotal excluding tax -->
<template x-if="segment.code === 'grand_total' && checkoutConfig.includeTaxInGrandTotal">
    <div>
        <div class="flex justify-end pt-2 my-2 mx-auto text-xl">
            <div class="text-left mr-2 font-sans text-xl leading-7 font-bold md:w-auto"
                 x-html="`${segment.title} ${includingTaxMessage}` "
            ></div>
            <div class="text-right font-sans text-xl leading-7 font-bold md:w-auto"
                 x-text="hyva.formatPrice(segment.value)"
            ></div>
        </div>

        <div class="flex justify-end pt-2 my-2 mx-auto mb-12 text-md">
            <div class="text-left mr-2 font-sans text-xl leading-7 font-bold md:w-auto"
                 x-html="`${segment.title} ${excludingTaxMessage}` "
            ></div>
            <div class="text-right font-sans text-xl leading-7 font-bold md:w-auto"
                 x-text="hyva.formatPrice(totalsData.grand_total)"
            ></div>
        </div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="segment.code === 'grand_total' && !checkoutConfig.includeTaxInGrandTotal">
    <div class="cart-grand-total flex justify-end p-2.5 mx-auto text-xl">
        <div class="text-left mr-2 font-sans text-xl leading-7 font-bold md:w-auto"
             x-html="`${segment.title}`"
        ></div>
        <div class="text-right font-sans text-xl leading-7 font-bold md:w-auto"
             x-text="hyva.formatPrice(segment.value)"
        ></div>
    </div>
</template>
