<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<!-- display subtotal including and excluding tax -->
<template x-if="segment.code === 'subtotal' && 'both' === checkoutConfig.reviewTotalsDisplayMode">
    <div class="hidden">
        <div class="flex justify-end text-md lg:text-sm">
            <div class="text-left mr-2 font-sans text-lg leading-6 font-bold md:w-auto"
                 x-html="`${segment.title} (${excludingTaxMessage})` "
            ></div>
            <div class="text-right font-sans text-lg leading-6 font-semibold md:w-auto"
                 x-text="hyva.formatPrice(totalsData.subtotal)"
            ></div>
        </div>

        <div class="flex justify-end text-md lg:text-sm">
            <div class="text-left mr-2 font-sans text-lg leading-6 font-bold md:w-auto"
                 x-html="`${segment.title} (${includingTaxMessage})` "
            ></div>
            <div class="text-right font-sans text-lg leading-6 font-semibold md:w-auto"
                 x-text="hyva.formatPrice(totalsData.subtotal_incl_tax)"
            ></div>
        </div>
    </div>
</template>

<!-- display subtotal excluding tax -->
<template x-if="segment.code === 'subtotal' && 'excluding' === checkoutConfig.reviewTotalsDisplayMode">
    <div class="flex justify-end text-md lg:text-sm hidden">
        <div class="text-left mr-2 font-sans text-lg leading-6 font-bold md:w-auto"
             x-html="`${segment.title}` "
        ></div>
        <div class="w-5/12 text-right font-sans text-lg leading-6 font-semibold md:w-auto"
             x-text="hyva.formatPrice(totalsData.subtotal)"
        ></div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="segment.code === 'subtotal' && 'including' === checkoutConfig.reviewTotalsDisplayMode">
    <div class="flex justify-end text-md lg:text-sm hidden">
        <div class="text-xl text-left mr-2 font-sans leading-6 font-semibold md:w-auto"
             x-html="`${segment.title}`"
        ></div>
        <div class="text-xl text-right font-sans leading-6 font-semibold md:w-auto"
             x-text="hyva.formatPrice(totalsData.subtotal_incl_tax)"
        ></div>
    </div>
</template>