<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentCategory;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\Block\Product\ListProduct;
use Magento\Framework\Escaper;

/** @var ListProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */
/** @var CurrentCategory $currentCategoryViewModel */

$productViewModel         = $viewModels->require(ProductPage::class);
$productListItemViewModel = $viewModels->require(ProductListItem::class);
$currentCategoryViewModel = $viewModels->require(CurrentCategory::class);

$hideRatingSummary = (bool) $block->getData('hide_rating_summary');
$hideDetails       = (bool) $block->getData('hideDetails');

$productCollection = $block->getLoadedProductCollection();

?>
<?php if (!$productCollection->count()): ?>
    <div class="message info empty">
        <div>
            <?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?>
        </div>
    </div>
<?php else: ?>
     <section class="pt-0 pb-8">
        <?php echo $this->getToolbarBlock()->setHidePager(true)->toHtml();?>
        <?= $block->getAdditionalHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode         = 'grid';
            $imageDisplayArea = 'category_page_grid';
            $showDescription  = false;
            $templateType     = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode         = 'list';
            $imageDisplayArea = 'category_page_list';
            $showDescription  = true;
            $templateType     = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="products wrapper mode-<?= /* @noEscape */$viewMode ?> products-<?= /* @noEscape */$viewMode ?>">
            <div class="mx-auto pt-4 pb-12 gap-8 <?= /* @noEscape */$viewMode === 'grid'
                ? 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3'
                : '' ?>">
                <?php /** @var \Magento\Catalog\Model\Product $product */ ?>
                <?php $i = 0;
                    foreach ($productCollection as $product): $i++;?>
                    <?= $productListItemViewModel->getItemHtml(
                        $product,
                        $block,
                        $viewMode,
                        $templateType,
                        $imageDisplayArea,
                        $showDescription
                    );?>
                    <?php if ($i === 3): ?>
                        <?php if($viewMode == 'list'):
                            $extraCSS = 'mb-8';
                        else:
                            $extraCSS = '';
                        endif; ?>
                        <div class="category-shop-block col-start-1 col-end-1 sm:col-end-3 sm:order-3 lg:order-none lg:col-end-4 <?= $extraCSS; ?>">
                            <?php echo $this->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('category-shopdeals')->toHtml(); ?>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category-usps')->toHtml(); ?>
        <?php echo $this->getToolbarBlock()->setHidePager(false)->toHtml();?>
    </section>
<?php endif; ?>
