<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\ConfigurableProduct\Block\Product\View\Type\Configurable;
use Magento\Framework\Escaper;

/** @var Configurable $block */
/** @var Escaper $escaper */

$product = $block->getProduct();
$productId = $product->getId();
$attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($product->isSaleable() && count($attributes)): ?>

    <script>
        function initConfigurableDropdownOptions_<?= (int) $productId ?>() {
            return initConfigurableOptions(
                '<?= (int) $productId ?>',
                <?= /* @noEscape */ $block->getJsonConfig() ?>
            );
        }
    </script>

    <div x-data="initConfigurableDropdownOptions_<?= (int) $productId ?>()"
         x-init="init();"
         @private-content-loaded.window="onGetCartData($event.detail.data)"
         class="mb-4 configurable-product-option flex flex-wrap"
    >
        <?php foreach ($attributes as $attribute): ?>
        <div class="flex flex-wrap md:mr-[30px] md:w-2/5 mb-2 w-full items-center">
            <label class="label text-gray-600 text-left w-full font-serif font-medium text-[black] text-lg"
                   for="attribute<?= $escaper->escapeHtmlAttr($attribute->getAttributeId()) ?>"
            >
                <span>
                    <?= $escaper->escapeHtml($attribute->getProductAttribute()->getStoreLabel()) ?>
                </span>
            </label>
            <div class="text-gray-900 text-left w-full">
                <select name="super_attribute[<?= $escaper->escapeHtmlAttr($attribute->getAttributeId()) ?>]"
                        id="attribute<?= $escaper->escapeHtmlAttr($attribute->getAttributeId()) ?>"
                        class="form-select super-attribute-select"
                        x-on:change="changeOption(<?= (int) $attribute->getAttributeId() ?>, event.target.value)"
                        required="required">
                    <option value="">
                        <?= $escaper->escapeHtml(__('Choose an Option')) ?>
                    </option>
                    <template
                        x-for="(item, index) in getAllowedAttributeOptions(<?= (int) $attribute->getAttributeId() ?>)"
                        :key="item.id"
                    >
                        <option
                            :value="item.id"
                            x-html="getAttributeOptionLabel(item)"
                            :selected="selectedValues[<?= $escaper->escapeHtmlAttr($attribute->getAttributeId()) ?>] ===
                                item.id">
                        </option>
                    </template>
                </select>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
<?php endif;?>
