<?php
/*
 * This program is the CONFIDENTIAL and PROPRIETARY property of Autify digital Ltd.
 * Any unauthorized use, reproduction or transfer of this computer program is strictly prohibited.
 * Copyright (c) 2020-2022 Autify digital Ltd.
 * This is an unpublished work, and is subject to limited distribution and restricted disclosure only.
 * ALL RIGHTS RESERVED.
 *
 */
$financeData = $this->getFinanceAnalyticsData();
$getGoogleMarketingConfig = $this->getGoogleMarketingConfig();

$googleAdwordsActive = $getGoogleMarketingConfig['google_adwords_active'];
$conversionId = $getGoogleMarketingConfig['google_adwords_conversion_id'];
$conversionLanguage = $getGoogleMarketingConfig['google_adwords_conversion_language'];
$conversionFormat = $getGoogleMarketingConfig['google_adwords_conversion_format'];
$conversionColor = $getGoogleMarketingConfig['google_adwords_conversion_color'];
$conversionLabel = $getGoogleMarketingConfig['google_adwords_conversion_label'];
$googleAnalyticsActive = $getGoogleMarketingConfig['google_analytics_active'];

if($googleAdwordsActive):
    $total = $financeData['order_amount'];
    ?>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = <?= $conversionId ?>;
        var google_conversion_language = "<?= $conversionLanguage ?>";
        var google_conversion_format = "<?= $conversionFormat ?>";
        var google_conversion_color = "<?= $conversionColor ?>";
        var google_conversion_label = "<?= $conversionLabel ?>";
        var google_remarketing_only = false;
        if (<?= $total?>) {
            var google_conversion_value = <?= $total?>;
        }
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/<?= $conversionId ?>/?label=<?= $conversionLabel ?>&amp;value=<?= $total?> &amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
<?php endif; ?>
