<?php
/** @var View $block */

use Actuate\RelevantProducts\ViewModel\RelevantProducts;
use Magento\Catalog\Block\Product\View;

/** @var RelevantProducts $relevantProductViewModel */
$relevantProductViewModel = $block->getData('relevantProductViewModel');

$product = $block->getProduct();
$currentSKU = $product->getId();
if ($product) {
    $relevantProducts = $relevantProductViewModel->getRelevantProductCollection($product);
    if (!empty($relevantProducts)):?>
    <div class="relevant-size mb-4">
        <div class="relevant-size-label block font-medium text-sm mb-2 text-black">
            <?php if (!empty($product->getAttributeText('nc1000000276'))): ?>
                <?= __('Choose Screen Size') ?>
            <?php elseif (!empty($product->getAttributeText('nc1000000828'))): ?>
                <?= __('Wash Load') ?>
            <?php endif; ?>
        </div>
        <div class="relevant-product-size flex">
        <?php foreach ($relevantProducts as $relevantProduct): ?>
            <?php // var_dump($relevantProduct); ?>
            <a class="py-1.5 w-1/4 mr-2 md:mr-4 last:mr-0 text-center text-[12px] md:text-[14px] font-medium bg-white border border-[#D1D5DB] md:border-white rounded-md <?php if($currentSKU == $relevantProduct['id']): echo 'pointer-events-none bg-[#000d40] text-white border-[#000d40]';  else: echo 'text-black border-[#D1D5DB] md:border-white'; endif; ?>" href="<?= $relevantProduct['productUrl']; ?>" title="<?= $relevantProduct['size']; ?>">
                <?= $relevantProduct['size']; ?>
            </a>
        <?php endforeach; ?>
        </div>
    </div>
    <?php endif; ?>
<?php
}