<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

// phpcs:disable Magento2.Files.LineLength.MaxExceeded

use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;

/** @var Renderer $block */
/** @var Escaper $escaper */

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

?>
<tbody class="cart item bg-white">
    <tr class="item-info align-top text-left lg:text-right flex flex-wrap lg:table-row p-2 md:p-0">
        <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>" class="col item pt-2 pr-1 flex flex-wrap gap-8 text-left w-1/3 md:pl-3 lg:pt-2 lg:pr-4 lg:w-auto">
            <?php if ($block->hasProductUrl()): ?>
                <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo  lg:flex-shrink-0">
            <?php else: ?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')
                ->setTemplate('Magento_Catalog::product/image.phtml')
                ->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
        </td>
        <td class="col pt-2 px-4 block w-full text-left w-2/3 lg:pt-2 lg:w-auto lg:table-cell relative">
            <div class="product-item-details flex-grow lg:mb-9">
                <strong class="product-item-name font-sans text-sm leading-5 font-normal lg:text-lg break-all">
                    <?php if ($block->hasProductUrl()): ?>
                        <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"><?= $escaper->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $escaper->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($options = $block->getOptionList()): ?>
                    <dl class="item-options w-full break-all mt-4 pb-2 text-sm clearfix">
                        <?php foreach ($options as $option): ?>
                            <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                            <dt class="font-bold float-left clear-left mr-2 mb-2"><?= $escaper->escapeHtml($option['label']) ?>:</dt>
                            <dd class="float-left font-sans text-sm leading-5 font-normal lg:font-normal">
                                <?php if (isset($formatedOptionValue['full_view'])): ?>
                                    <?= $escaper->escapeHtml($formatedOptionValue['full_view'], ['ul', 'li']) ?>
                                <?php else: ?>
                                    <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class= "cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $escaper->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($item)->toHtml() ?>
                <?php endif;?>
            </div>
            <div class="absolute lg:static top-full right-0 lg:pt-0 ml-10 lg:ml-0">
                <div class="field qty lg:inline-block !mt-0">
                    <div class="control qty">
                        <label class="flex" for="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty">
                            <div class="value-button" id="decrease" onclick="decreaseValue(<?= $escaper->escapeHtmlAttr($item->getId()) ?>)" value="Decrease Value">-</div>
                            <input id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty"
                                name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]"
                                value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                                type="number"
                                size="4"
                                step="any"
                                title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                                class="qty-box qty form-input px-2 py-2 w-20 text-center max-w-[70px] md:max-w-auto"
                                required="required"
                                min="0"
                                @change.debounce.2000ms="$event.target.form && $event.target.form.dispatchEvent(new Event('submit', { cancelable: true }));"
                                data-role="cart-item-qty"/>
                            <div class="value-button" id="increase" onclick="increaseValue(<?= $escaper->escapeHtmlAttr($item->getId()) ?>)" value="Increase Value">+</div>
                        </label>
                    </div>
                </div>
                <script>
                    function increaseValue(id) {
                        var value = parseInt(document.getElementById('cart-'+ id + '-qty').value, 10);
                        value = isNaN(value) ? 0 : value;
                        value++;
                        document.getElementById('cart-'+ id + '-qty').value = value;
                        triggerShoppingCartUpdate();
                    }

                    function decreaseValue(id) {
                        var value = parseInt(document.getElementById('cart-'+ id + '-qty').value, 10);
                        value = isNaN(value) ? 0 : value;
                        value < 1 ? value = 1 : '';
                        value--;
                        document.getElementById('cart-'+ id + '-qty').value = value;
                        triggerShoppingCartUpdate();
                    }
                    function triggerShoppingCartUpdate() {
                        document.querySelector('button[name="update_cart_action"]').click();
                    }
                </script>
            </div>
            <?php
                $_promo1 = $product->getAttributeText('nc1000000352');
                $_promo2 = $product->getAttributeText('nc1000000466');
                $_promo3 = $product->getAttributeText('nc1000000470');
                $_promo4 = $product->getAttributeText('nc1000001270');
                $_promo5 = $product->getAttributeText('nc1000001276');
                if ($_promo1 == 'x' || $_promo1 == 'X'):
                    $_promo1 = '';
                endif;
                if ($_promo2 == 'x' || $_promo2 == 'X'):
                    $_promo2 = '';
                endif;
                if ($_promo3 == 'x' || $_promo3 == 'X'):
                    $_promo3 = '';
                endif;
                if ($_promo4 == 'x' || $_promo4 == 'X'):
                    $_promo4 = '';
                endif;
                if ($_promo5 == 'x' || $_promo5 == 'X'):
                    $_promo5 = '';
                endif;
                //$_promo1 = 'samsung150av';
            ?>
            <?php
                $deal1content = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('deal-' . $_promo1 . '')->toHtml();
                $deal2content = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('deal-' . $_promo2 . '')->toHtml();
                $deal3content = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('deal-' . $_promo3 . '')->toHtml();
                if($deal1content != ''):
                    if (str_contains($deal1content, 'pdp-deal-link')):
                        $deal1content = $deal1content;
                    else:
                        $deal1content = '<span class="pdp-deal-link">'.$deal1content.'</span>';
                    endif;
                    echo '<div class="deal-1 pdp-deal-strip cursor-pointer mt-2.5">'.$deal1content.'</div>';
                elseif($deal2content != ''):
                    if (str_contains($deal2content, 'pdp-deal-link')):
                        $deal2content = $deal2content;
                    else:
                        $deal2content = '<span class="pdp-deal-link">'.$deal2content.'</span>';
                    endif;
                    echo '<div class="deal-2 pdp-deal-strip cursor-pointer mt-2.5">'.$deal2content.'</div>';
                elseif($deal3content != ''):
                    if (str_contains($deal3content, 'pdp-deal-link')):
                        $deal3content = $deal3content;
                    else:
                        $deal3content = '<span class="pdp-deal-link">'.$deal3content.'</span>';
                    endif;
                    echo '<div class="deal-3 pdp-deal-strip cursor-pointer mt-2.5">'.$deal3content.'</div>';
                endif;
            ?>
        </td>
        <td class="hidden col price pt-2 px-4 block w-full w-1/3 font-sans text-sm leading-5 font-normal lg:text-lg lg:hidden lg:w-auto lg:table-cell">
            <span class="lg:hidden mt-2 font-sans text-base leading-6 font-bold">
                <?= $escaper->escapeHtml(__('Price')) ?>
            </span>
            <?= $block->getUnitPriceHtml($item) ?>
        </td>

        <td class="col subtotal md:pt-2 px-4 block w-full font-sans text-sm leading-5 font-normal lg:text-lg w-1/3 lg:w-auto lg:table-cell ml-auto">
            <span class="lg:hidden hidden font-sans text-base leading-6 font-bold">
                <?= $escaper->escapeHtml(__('Subtotal')) ?>
            </span>
            <?= $block->getRowTotalHtml($item) ?>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="4">
            <div class="flex justify-end gap-4 p-4 pt-2">
                <?= /* @noEscape */ $block->getActions($item) ?>
            </div>
        </td>
    </tr>
</tbody>