<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($block->isContentMode() || $block->isMixedMode()) :?>
    <div class="category-cms" x-data="initReadMore()" x-init="initReadMore()">
        <div class="category-cms-content" :class="{'max-h-[400px] overflow-hidden': isReadMoreVisible && isReadMore}">
            <?php
            $seoblock = 'override-'.parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
            $seoblock = str_replace('/','-',$seoblock);
            if ($this->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId($seoblock)->toHtml() != ''):
                echo $this->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId($seoblock)->toHtml();
            else: ?>
                <?= $block->getCmsBlockHtml(); ?>
            <?php endif; ?>
        </div>
        <template x-if="isReadMoreVisible">
            <template x-if="isReadMore">
                <div class="w-100 flex justify-center items-center cursor-pointer py-2.5" @click="isReadMore=!isReadMore">
                    <span class="text-[#126366] px-2.5 font-medium">Read more</span>
                    <svg width="14" height="9" viewBox="0 0 14 9" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M1 1.00006L7 7.00006L13 1.00006" stroke="#126366" stroke-width="2" stroke-linecap="round"/>
                    </svg>
                </div>
            </template>
            <template x-if="!isReadMore">
                <div class="w-100 flex justify-center items-center cursor-pointer py-2.5" @click="isReadMore=!isReadMore">
                    <span class="text-[#126366] px-2.5 font-medium">Read Less</span>
                    <svg width="14" height="9" viewBox="0 0 14 9" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M13 7L7 0.999999L1 7" stroke="#126366" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </div>
            </template>
        </template>
    </div>
    <script>
        function initReadMore () {
            return {
                "isReadMoreVisible": false,
                "isReadMore": true,
                initReadMore: function () {
                    this.isReadMoreVisible = document.querySelector('.category-cms-content').offsetHeight >= 400;
                }
            }
        }
    </script>
<?php endif; ?>
