<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/**
 * @Internal Prefer utilizing the "after" container for injecting additional code.
 */
?>
<script>
    'use strict';

    (() => {
        window.addEventListener('checkout:init:loader', () => {
            <?php /* Configure the native loading behavior for the Hyvä Checkout. */ ?>
            hyvaCheckout.loader.set({
                start: () => window.dispatchEvent(new Event('checkout:loader:start')),
                stop:  () => window.dispatchEvent(new Event('checkout:loader:stop'))
            })
        })
    })()
</script>

<?= $this->getChildHtml('after') ?>
