<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/**
 * @Internal Prefer utilizing the "after" container for injecting additional code.
 */
?>
<script>
    'use strict';

    (() => {
        <?php /* Optimizing API performance by preconfiguring settings. This approach eliminates the need to wait for
               * the initialization of the "config" component, significantly enhancing the overall efficiency.
               * We strategically listen for the initialization of the Main component, acting as the first critical
               * step in the process. Once this initialization is complete, we promptly set up the configuration object.
               * This object is retrieved from the Main component server memo, ensuring seamless and expedited
               * configuration readiness. */ ?>
        window.addEventListener('checkout:init:main', event => {
            try {
                const main = event.detail.namespace
                const wireComponent = main.getWireComponent()
                const wireComponentInstance = wireComponent.__instance

                <?php /* Pre-fill the configuration before the API is being initialized. */ ?>
                hyvaCheckout.config.config = wireComponentInstance.data.config
            } catch (exception) {
                console.error(exception)
            }
        })
    })()
</script>

<?= $this->getChildHtml('after') ?>
