<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Tax\Model\Config as TaxConfig;

/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var TaxConfig $taxConfig */
/** @var HeroiconsOutline $heroiconsViewModel */

$icons = $viewModels->require(HeroiconsOutline::class);
$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$segment = $block->getSegment();
$taxConfig = $block->getTaxConfig();

?>
<?php if ($segment && $taxConfig && $taxConfig->displayCartFullSummary()): ?>
<div x-data="{ expand: false }">
    <header>
        <button type="button"
                class="flex items-center justify-between w-full focus:outline-none"
                x-on:click="expand = ! expand"
                x-bind:title="expand ? '<?= $escaper->escapeHtml(__('Hide items')) ?>' : '<?= $escaper->escapeHtml(__('Show items')) ?>'"
        >
            <div class="flex relative">
                <?= $escaper->escapeHtml(__('Tax Breakdown')) ?>
            </div>

            <span :class="{ 'transform rotate-180': expand }">
                <?= $icons->chevronDownHtml('w-4 h-4', 16, 16) ?>
            </span>
        </button>
    </header>

    <ul x-show="expand" x-cloak>
        <?php foreach ($segment as $key => $item): ?>
            <?php $rates = array_filter($item['rates'] ?? [], fn ($rate) => ! (($rate['hidden'] ?? false) === true)) ?>
            <?php if (empty($rates)): continue; endif ?>
            <?php $percentage = array_sum(array_column($item['rates'], 'percent')) ?>

            <?php foreach ($rates as $rate): ?>
                <li class="flex gap-4 justify-between md:gap-0">
                    <span class="tax-label">
                        <?= $escaper->escapeHtml($rate['title']) ?>

                        <?php if ($rate['percent']): ?>
                            <span class="tax-percentage">
                                ( <?= (float) $rate['percent'] ?>% )
                            </span>
                        <?php endif ?>
                    </span>

                    <?php if ($key === 0): ?>
                        <span class="tax-unit">
                            <?= /* @noEscape */ $formatterViewModel->currency(($item['amount'] * (float) $rate['percent']) / $percentage) ?>
                        </span>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>
