<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */


$availableLimitOptions = $block->getAvailableLimit();

?>

<?php if (count($availableLimitOptions) > 1): ?>
    <div class="field limiter flex items-center order-2 justify-start hidden lg:block">
        <div class="control">
            <label class="text-sm label">
                <span class="text-sm font-sans leading-5 font-medium pr-4 hidden 2xl:inline-block"><?= $escaper->escapeHtml((string)__('Show')) ?></span>

                <select data-role="limiter" class="form-select limiter-options font-serif text-sm leading-5 font-medium border-gray-500 h-[46px] max-w-[184px]"
                    @change="changeUrl(
                    'product_list_limit',
                    $event.currentTarget.options[$event.currentTarget.selectedIndex].value,
                    options.limitDefault
                )">
                <?php foreach ($block->getAvailableLimit() as $key => $limit): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($key) ?>"
                        <?php if ($block->isLimitCurrent($key)): ?>
                            selected="selected"
                        <?php endif ?>>
                        <?= $escaper->escapeHtml($limit) ?> <?= $escaper->escapeHtml((string)__('products per page')) ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </label>
        </div>
        <span class="limiter-text text-sm ml-2 sr-only">
            <?= $escaper->escapeHtml(__('per page')) ?>
        </span>
    </div>
<?php else: ?>
    <div class="field limiter flex order-3 sm:order-2 md:order-3 lg:order-2 col-span-2 justify-end">

    </div>
<?php endif;
