<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */
?>
<?php if ($block->isEnabledViewSwitcher()): ?>

    <?php $modes = $block->getModes(); ?>
    <?php if ($modes && count($modes) > 1): ?>
        <div class="modes flex space-x-3 items-center px-2 py-2 text-sm leading-5 order-1 col-span-2 lg:order-4 md:col-span-1 justify-end">
            <strong class="modes-label text-sm font-sans leading-5 font-medium pr-0"><?= $escaper->escapeHtml((string)__('View as')) ?></strong>
            <?php foreach ($block->getModes() as $code => $label): ?>
                <?php if ($block->isModeActive($code)): ?>
                    <strong title="<?= $escaper->escapeHtmlAttr($label) ?>"
                            class="modes-mode text-[#E8983F] active mode-<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>"
                            data-value="<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>">
                        <span><?= $escaper->escapeHtml($label) ?></span>
                        <?php if($escaper->escapeHtmlAttr(strtolower($code)) == 'grid'): ?>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-5 h-5"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" /></svg>
                        <?php else: ?>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-5 h-5"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 10h16M4 14h16M4 18h16" /></svg>
                        <?php endif; ?>
                    </strong>
                <?php else: ?>
                    <a class="modes-mode mode-<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>
                        opacity-25 hover:opacity-100"
                       title="<?= $escaper->escapeHtmlAttr($label) ?>"
                       href="#"
                       @click.prevent="changeUrl(
                        'product_list_mode', '<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>', options.modeDefault
                       )"
                       data-role="mode-switcher"
                       data-value="<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>"
                       aria-label="<?= $escaper->escapeHtmlAttr($label) ?>">
                        <span><?= $escaper->escapeHtml($label) ?></span>
                        <?php if($escaper->escapeHtmlAttr(strtolower($code)) == 'grid'): ?>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-5 h-5"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" /></svg>
                        <?php else: ?>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-5 h-5"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 10h16M4 14h16M4 18h16" /></svg>
                        <?php endif; ?>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

    <?php else: ?>
        <div class="modes w-20 order-1 col-span-1 sm:col-span-2 md:col-span-1 lg:col-span-2"></div>
    <?php endif; ?>

<?php endif; ?>
