<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Actuate\Option\ViewModel\OptionTooltipViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPrice;
use Magento\Catalog\Block\Product\View\Options\Type\Select\Checkable;
use Magento\Catalog\Model\Product\Option;
use Magento\Catalog\Pricing\Price\CustomOptionPrice;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/**
 * @var Checkable $block
 * @var Escaper $escaper
 * @var ViewModelRegistry $viewModels
 * @var SecureHtmlRenderer $secureRenderer
 */

$product = $block->getProduct();

/** @var ProductPrice $productPriceViewModel */
$productPriceViewModel = $viewModels->require(ProductPrice::class);
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var OptionTooltipViewModel $optionViewModel */
$optionViewModel = $viewModels->require(OptionTooltipViewModel::class);

$option = $block->getOption();

if ($option): ?>
    <?php
    $configValue = $block->getPreconfiguredValue($option);
    $optionType = $option->getType();
    $arraySign = $optionType === Option::OPTION_TYPE_CHECKBOX ? '[]' : '';
    $count = 1;
    ?>

<div class="options-list nested" id="options-<?= $escaper->escapeHtmlAttr($option->getId()) ?>-list">
    <?php if ($optionType === Option::OPTION_TYPE_RADIO && !$option->getIsRequire()): ?>
    <div class="field choice">
        <input type="radio"
               id="options_<?= $escaper->escapeHtmlAttr($option->getId()) ?>"
               class="radio product-custom-option"
               name="options[<?= $escaper->escapeHtmlAttr($option->getId()) ?>]"
               value=""
               checked="checked"
               x-on:change="updateCustomOptionValue(
                $dispatch, '<?= $escaper->escapeHtmlAttr($option->getId()) ?>', $event.target
               )"
        />
        <label class="label text-left font-serif font-medium"
               for="options_<?= $escaper->escapeHtmlAttr($option->getId()) ?>">
            <span>
                <?= $escaper->escapeHtml(__('None'))  ?>
            </span>
        </label>
    </div>
<?php endif; ?>
    <?php foreach ($option->getValues() as $value): ?>
        <?php
        $checked = '';
        $count++;
        if ($arraySign) {
            $checked = is_array($configValue) && in_array($value->getOptionTypeId(), $configValue) ? 'checked' : '';
        } else {
            $checked = $configValue == $value->getOptionTypeId() ? 'checked' : '';
        }
        $dataSelector = 'options[' . $option->getId() . ']';
        if ($arraySign) {
            $dataSelector .= '[' . $value->getOptionTypeId() . ']';
        }

        $optionId = $option->getId() . '_' . $value->getOptionTypeId();

        $valuePrice = $productPriceViewModel->getCustomOptionPrice($value, CustomOptionPrice::PRICE_CODE, $product);

        if (str_contains($value->getTitle(), 'Setup')):
            $info_type = 'setup';
        elseif (str_contains($value->getTitle(), 'Packaging')):
            $info_type = 'packaging';
        elseif (str_contains($value->getTitle(), 'Disposal')):
            $info_type = 'disposal';
        else:
            $info_type = '';
        endif;
        ?>

        <div class="field choice">
            <input type="<?= $escaper->escapeHtmlAttr($optionType) ?>"
                   class="<?= $optionType === Option::OPTION_TYPE_RADIO
                       ? 'form-radio'
                       : 'form-checkbox' ?>
                       product-custom-option"
                   name="options[<?= $escaper->escapeHtmlAttr($option->getId()) ?>]<?= /* @noEscape */ $arraySign ?>"
                   id="options_<?= $escaper->escapeHtmlAttr($optionId) ?>"
                   value="<?= $escaper->escapeHtmlAttr($value->getOptionTypeId()) ?>"
                   <?= $escaper->escapeHtml($checked) ?>
                   x-ref="option-<?= $escaper->escapeHtmlAttr($option->getId() . '-' . $value->getOptionTypeId()) ?>"
                   <?php if ($option->getIsRequire()): ?>
                       required
                       data-required
                       oninvalid="this.setCustomValidity(this.dataset.validationMessage)"
                       oninput="this.setCustomValidity('')"
                       data-validation-message="<?= $escaper
                           ->escapeHtmlAttr(__("Please select one of the options.")) ?>"
                    <?php endif; ?>
                   data-price-amount="<?= $escaper->escapeHtmlAttr($valuePrice) ?>"
                   data-price-type="<?= $escaper->escapeHtmlAttr($value->getPriceType()) ?>"
                   data-option-id="<?= $escaper->escapeHtmlAttr($optionId) ?>"
                   x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>"
                   x-on:change="updateCustomOptionValue(
                    $dispatch, '<?= $escaper->escapeHtmlAttr($optionId) ?>', $event.target
                   )"
            />
            <label class="label text-left font-serif font-medium"
                   for="options_<?= $escaper->escapeHtmlAttr($optionId) ?>"
            >
                <span><?= $escaper->escapeHtml($value->getTitle()) ?></span>
                <span x-html="getFormattedOptionPrice('<?= $escaper->escapeHtmlAttr($optionId) ?>') || ''">
                    <?= /* @noEscape */ $block->formatPrice($value) ?>
                </span>

            </label>
            <span class="inline-flex relative">
                <span class="info_<?= $escaper->escapeHtmlAttr($count) ?> ml-2 peer cursor-pointer rounded-md bg-neutral-50 font-medium tracking-wide text-neutral-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-black dark:bg-neutral-900 dark:text-neutral-300 dark:focus-visible:outline-white" id="option_for_<?= $info_type; ?>">
                    <?= $heroicons->informationCircleHtml('w-4 h-4 text-black'); ?>
                </span>
                <?php if($identifier = $optionViewModel->getOptionTooltip($value->getDescription())): ?>
                    <div class="tooltipOptions pointer-events-none absolute bottom-full mb-2 left-1/2 -translate-x-1/2 z-10 flex md:w-[450px] w-64 flex-col gap-1 rounded bg-[#000000] p-2.5 md:text-sm text-xs text-neutral-300 opacity-0 transition-all ease-out peer-hover:opacity-100 peer-focus:opacity-100" role="tooltip">
                        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($identifier)->toHtml(); ?>
                    </div>
                <?php endif;?>
            </span>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif; ?>
