<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$element = $block->getData('element');
?>
<?php if ($element->hasComment()): ?>
    <p class="mt-2 text-sm comment">
        <?= $escaper->escapeHtml(__($element->getComment())) ?>
    </p>
<?php endif ?>
