<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Checkout\Block\Onepage\Success;
use Actuate\ReliantDirectTheme\Helper\Data;

/** @var Success $block */
/** @var Escaper $escaper */

/** @var Data $successHelper */
$successHelper = $this->helper(Data::class);
$order = $successHelper->getOrderByIncrementId($block->getOrderId());
?>
<div class="checkout-success container py-4 px-6">
    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getCanViewOrder()): ?>
            <p>
                <?= $escaper->escapeHtml(
                    __(
                        'Your order number is: %1.',
                        sprintf(
                            '<a href="%s" class="order-number"><strong>%s</strong></a>',
                            $escaper->escapeUrl($block->getViewOrderUrl()),
                            $block->getOrderId()
                        )
                    ),
                    ['a', 'strong']
                ) ?>
            </p>
        <?php  else: ?>
            <p><?= $escaper->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
        <p>
            <?= $escaper->escapeHtml(
                __('We\'ll email you an order confirmation with details and tracking info.')
            ) ?>
        </p>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="my-4">
        <a class="btn btn-primary inline-flex" href="<?= $escaper->escapeUrl($block->getContinueUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span>
        </a>
    </div>
    <!-- Event snippet for Purchase conversion page -->
    <script>
        gtag('event', 'conversion', {
            'send_to': 'AW-994909143/91kbCKLa31YQ17e02gM',
            'value': <?= /* @noEscape */ $order->getGrandTotal(); ?>,
            'currency': 'GBP',
            'transaction_id': '<?= /* @noEscape */ $order->getIncrementId() ?>'
        });
    </script>
    <script> window.uetq = window.uetq || []; window.uetq.push('event', '', {"revenue_value":<?= /* @noEscape */ $order->getGrandTotal(); ?>,"currency":"GBP"}); </script>
</div>
