<?php
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2020 JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */

/** @var $block \Jajuma\WebpImages\Block\Picture */
$customSrcTag = $block->getCustomSrcTag();
$customSrcSetTag = $block->getCustomSrcSetTag();

$originalTag = $block->getOriginalTag();
$originalSrc = $block->getOriginalImage();
$srcsetTag = $block->getCustomSrcSetTag() ? $block->getCustomSrcSetTag() : "srcset";

$isLazyLoadEnabled = $block->isNativeLazyLoadingEnabled();
$excludeNativeLazyloadImageAttributes = $block->getExcludeNativeLazyloadImageAttributes();
$isImageInExcludeList = preg_match_all($excludeNativeLazyloadImageAttributes, $originalTag);

if ($isLazyLoadEnabled && !$isImageInExcludeList) {
    // add loading="lazy" at the end of the img tag
    $originalTag = preg_replace('/>$/', ' loading="lazy" />', $originalTag);
}

$webpSrcset = false;

if(strpos($originalSrc, 'small_image') !== false && strpos($originalSrc, 'item') === false) {
    //Slider Images
    $webpSrcset = "product.small_image.url_webp !== 'false' ? product.small_image.url_webp : ''";
}

if(strpos($originalSrc, 'small_image') !== false && strpos($originalSrc, 'packProduct') !== false && strpos($originalSrc, 'item') === false) {
    //Slider Images
    $webpSrcset = "packProduct.product.small_image.url_webp !== 'false' ? packProduct.product.small_image.url_webp : ''";
}

if(strpos($originalSrc, 'fullscreen') !== false) {
    //Gallery Images
    $webpSrcset = "fullscreen ? image.full_webp : image.img_webp";
}

if(strpos($originalSrc, 'thumb') !== false) {
    //Gallery Thumbs
    $webpSrcset = "image.thumb_webp";
}
?>
<?php if($webpSrcset): ?>
    <picture>
        <source type="image/webp" :<?= /* @noEscape */ $srcsetTag?>="<?= /* @noEscape */ $webpSrcset?>">
        <source type="" :<?= /* @noEscape */ $srcsetTag?>="<?= /* @noEscape */ $originalSrc ?>">
        <?= /* @noEscape */ $originalTag ?>
    </picture>
<?php else: ?>
    <?= /* @noEscape */ $originalTag ?>
<?php endif ?>

