<?php
/** @var \Actuate\MirasvitSeoFilter\Block\Adminhtml\Attribute\Edit\Tab\Fieldset\CategoryFieldSet $block */
$categories = $block->getOptions();
$categoryIds = !empty($categories) ? implode(',', $categories) : null;
?>
<div class="fieldset">
    <div class="grid">
        <div class="hor-scroll">
            <div class="admin__field field">
                <label class="label admin__field-label"><?= __('Category IDs')?></label>
                <div class="admin__field-control control">
                    <textarea name="seo_filter[category_ids]" class="input-text admin__control-text"><?= $categoryIds ?></textarea>
                    <small>Please add comma separated category ids... For eg. 357,415</small>
                </div>
            </div>
        </div>
    </div>
</div>
