<?php
/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Renderer\CategoryRenderer
 * @var $escaper \Magento\Framework\Escaper
 */

use Actuate\MirasvitSeoFilter\ViewModel\FilterOptionViewModel;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var ViewModelRegistry $viewModels */
/** @var FilterOptionViewModel $heroicons */
$filterOptionViewModel = $viewModels->require(FilterOptionViewModel::class);

$attributeCode = $block->getAttributeCode();
$filterAccessor = $attributeCode;
$lastLevel     = 0;
$filterItems   = $block->getFilterItems();
$filterOptionIndexFlag = $filterOptionViewModel->getExistsOptions($attributeCode);
?>
<div data-mst-nav-filter="<?= $filterAccessor ?>" class="mst-nav__label mst-nav__category" x-data="initLabelRenderer()">
    <?= $block->getSearchBoxElement($filterAccessor) ?>

    <ol class="items">
        <?php foreach ($filterItems as $key => $filterItem):
            $label = $filterItem->getData('label');
            $numberOfResults = $filterItem->getData('count');
            $level = $filterItem->getData('level');
	    $isParent = $filterItem->getData('is_parent');

            $isItemChecked = $block->isFilterItemChecked($filterItem, true);

            $cssClass = [
                'item',
                'mst-nav__label-item',
                '_mode-' . $block->getFilterItemDisplayMode('category_ids'),
                $isItemChecked ? '_checked' : '',
                $isItemChecked && $block->isHighlightEnabled() ? '_highlight' : '',
                $isParent ? '_parent' : '',
            ];
            ?>

            <?= $level > $lastLevel
            ? str_repeat('<ol class="items">', $level - $lastLevel)
            : str_repeat('</ol>', $lastLevel - $level)
            ?>

            <li data-element="filter"
                data-value="<?= $filterItem->getValueString() ?>"
                class="<?= implode(' ', $cssClass) ?>"
                @click="handleClick"
            >
                <?php if ($numberOfResults >= 0): ?>
                    <?php
                    $url = $isItemChecked ? $filterItem->getRemoveUrl() : $filterItem->getUrl();
                    $id  = $block->getItemId($filterItem);
                    $relAttributeValue = $block->getRelAttributeValue();
                    if (isset($filterOptionIndexFlag[$filterItem->getValueString()])
                        && $filterOptionIndexFlag[$filterItem->getValueString()] === '1') {
                        $relAttributeValue = 'follow';
                    }
                    ?>
                    <a href="<?= $filterItem->getData('count') > 0 ? $escaper->escapeUrl($url) : '#' ?>"
                       rel="<?= $relAttributeValue ?>"
                       aria-label="<?= $escaper->escapeHtmlAttr($label) ?>"
                    >
                        <input id="<?= $id ?>" type="checkbox" <?= $isItemChecked ? 'checked' : '' ?>
                            <?= $filterItem->getData('count') == 0 ? 'disabled' : '' ?> />

                        <label for="<?= $id ?>">
                            <span class="mst-nav__label-item__label"><?= $label ?></span>
                            <span class="count text-primary">(<?= $filterItem->getData('count') ?>)</span>
                        </label>
                    </a>
                <?php else: ?>
                    <span class="mst-nav__label-item__label"><?= $label ?></span>
                    <span class="count text-primary">(<?= $filterItem->getData('count') ?>)</span>
                <?php endif ?>
            </li>
            <?php $lastLevel = $level ?>
        <?php endforeach ?>

        <?= $block->getSizeLimiterElement($filterAccessor) ?>
    </ol>
</div>

<style>
    .mst-nav__category ol.items {
        margin-left: 1.5rem;
    }

    .mst-nav__category ol.items:first-child {
        margin-left: 0;
    }
</style>
