<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Magewire\Checkout\PriceSummary\CartItems;
use Hyva\Checkout\ViewModel\Checkout\PriceSummary\CartItems as CartItemsViewModel;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Tax\Helper\Data as TaxHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
/** @var Escaper $escaper */
/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $icons */
/** @var CartItems $magewire */
/** @var CartItemsViewModel $cartItemsViewModel */
/** @var TaxHelper $taxHelper */

$icons = $viewModels->require(HeroiconsOutline::class);
$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$cartItemsViewModel = $viewModels->require(CartItemsViewModel::class);
$taxHelper = $this->helper(TaxHelper::class);

$quoteItems = $magewire->getQuoteItemData();
?>
<div x-data="{ expand: $wire.expand }" class="!mt-0">
    <?php if ($quoteItems): ?>
        <div class="cart-items md:max-h-[34vh] md:overflow-auto"
             x-cloak
        >
            <div class="flex flex-col h-full space-y-6">
                <div class="relative grid">
                    <?php foreach ($quoteItems as $item): ?>
                        <div class="flex gap-4 py-5 border-b border-[#cccccc] last:border-b-0">
                            <div class="flex-none relative max767:max-w-[43%]">
                                <img src="<?= $escaper->escapeUrl($item['thumbnail']) ?>"
                                     width="188"
                                     height="139"
                                     alt="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
                                     loading="lazy"
                                     class="rounded-md"
                                />
                            </div>

                            <div class="flex-grow space-y-2">
                                <div class="gap-4 md:gap-0">
                                    <div class="product-title">
                                        <p class="font-normal text-[19px] leading-[22px]">
                                            <?= $escaper->escapeHtml($item['name']) ?>
                                        </p>

                                        <p class="mt-2.5 text-[19px] leading-[22px]">
                                            Qty: <?= /* @noEscape */ $item['qty'] ?>
                                        </p>
                                    </div>

                                    <div class="product-price text-[22px] mt-2">
                                        <?php if ($taxHelper->displayCartPriceInclTax() || $taxHelper->displayCartBothPrices()): ?>
                                            <span class="price-including-tax" data-label="<?= $escaper->escapeHtmlAttr(__('Incl. Tax')) ?>">
                                                <?= /* @noEscape */ $formatterViewModel->currency($item['row_total_incl_tax']) ?>
                                            </span>
                                        <?php endif; ?>

                                        <?php if ($taxHelper->displayCartPriceExclTax() || $taxHelper->displayCartBothPrices()): ?>
                                            <span class="price-excluding-tax" data-label="<?= $escaper->escapeHtmlAttr(__('Excl. Tax')) ?>">
                                                <?= /* @noEscape */ $formatterViewModel->currency($item['row_total']) ?>
                                            </span>
                                        <?php endif; ?>
                                    </div>
                                </div>

                                <?php $optionsRenderer = $cartItemsViewModel->getProductOptionsRenderer($block, $item['product_type']) ?>
                                <?php if ($optionsRenderer): ?>
                                    <?= /* @noEscape */ $optionsRenderer->setData('quote_item', $item)->toHtml() ?>
                                <?php endif ?>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    <?php endif ?>
</div>
