<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Paypal\Block\Express\Review;

/**
 * @var Review $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Paypal\ViewModel\PaypalFundingSourceDataProvider $paypalFundingSourceDataProvider */
$paypalFundingSourceDataProvider = $block->getData('PaypalFundingSourceDataProvider');
?>
<div class="paypal-review view">
     <div class="mobile-estimated-wrapper">
        <div class="paypal-minicart-wrapper">
            <button type="button" class="show-cart-btn">Show Order Details</button>
        </div>
        <div class="estimated-block">
            <span class="estimated-label">Estimated Total</span>
            <span class="estimated-price">
                <?php
                    $cartHelper = $this->helper(\Magento\Checkout\Helper\Cart::class);
                    $priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
                    echo $priceHelper->currency($cartHelper->getQuote()->getGrandTotal(), true, false);
                ?>
            </span>
        </div>
     </div>
    <div class="block block-order-details-view">
        <div class="block-content">
            <?php if ($block->getShippingAddress()): ?>
                <div class="box box-order-shipping-method">
                    <strong class="box-title">
                        <span><?= $escaper->escapeHtml(__('Shipping Method')) ?></span>
                    </strong>
                    <div class="box-content">
                        <form method="post" id="shipping-method-form"
                              action="<?= $escaper->escapeUrl($block->getShippingMethodSubmitUrl()) ?>"
                              class="form">
                            <?php if ($block->canEditShippingMethod()): ?>
                                <?php if ($groups = $block->getShippingRateGroups()): ?>
                                    <?php $currentRate = $block->getCurrentShippingRate(); ?>
                                    <div class="field shipping required">
                                        <select name="shipping_method" id="shipping-method" class="select">
                                            <?php if (!$currentRate): ?>
                                                <option value="">
                                                    <?= $escaper->escapeHtml(
                                                        __('Please select a shipping method...')
                                                    ); ?>
                                                </option>
                                            <?php endif; ?>
                                            <?php foreach ($groups as $code => $rates): ?>
                                                <?php foreach ($rates as $rate): ?>
                                                    <option value="<?=
                                                                    $block->escapeHtml(
                                                                        $block->renderShippingRateValue($rate)
                                                                    );
                                                                    ?>"
                                                        <?= ($currentRate === $rate) ?
                                                            ' selected="selected"' : '';
                                                        ?>>
                                                        <?= /* @noEscape */ $block->renderShippingRateOption($rate);
                                                        ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="actions-toolbar"></div>
                                <?php else: ?>
                                    <p>
                                        <?= $escaper->escapeHtml(__(
                                            'Sorry, no quotes are available for this order right now.'
                                        )); ?>
                                    </p>
                                <?php endif; ?>
                            <?php else: ?>
                                <p>
                                    <?= /* @noEscape */ $block->renderShippingRateOption(
                                        $block->getCurrentShippingRate()
                                    ); ?>
                                </p>
                            <?php endif; ?>
                        </form>
                    </div>
                </div>
                <div class="box box-order-shipping-address">
                    <strong class="box-title">
                        <span><?= $escaper->escapeHtml(__('Shipping Address')) ?></span>
                    </strong>
                    <div class="box-content">
                        <address>
                            <?= $escaper->escapeHtml(
                                $block->renderAddress($block->getShippingAddress()),
                                ['br']
                            ); ?>
                        </address>
                        <?php if ($block->getCanEditShippingAddress()): ?>
                            <div class="box-actions">
                                <a href="<?= $escaper->escapeUrl($block->getEditUrl()) ?>" class="action edit">
                                    <span><?= $escaper->escapeHtml(__('Edit')) ?></span>
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="box box-order-billing-address">
                <strong class="box-title"><span><?= $escaper->escapeHtml(__('Payment Method')) ?></span></strong>
                <div class="box-content">
                    <img src="<?php echo $this->getViewFileUrl('images/paypal.png'); ?>"
                         alt="<?= $block->escapeHtml(__('Buy now with PayPal')) ?>"/>
                    <strong>
                        <?= $escaper->escapeHtml($paypalFundingSourceDataProvider->getPaypalFundingSource()
                        ?? $block->getPaymentMethodTitle()) ?>
                    </strong>
                    <p>
                        <?= $escaper->escapeHtml($block->getEmail()) ?>
                    </p>
                </div>
                <?php if ($block->getEditUrl()): ?>
                    <div class="box-actions">
                        <a class="button action primary" href="<?= $escaper->escapeUrl($block->getEditUrl()) ?>" class="action edit">
                            <span><?= $escaper->escapeHtml(__('Edit Payment Information')) ?></span>
                        </a>
                    </div>
                <?php endif ?>
            </div>
        </div>
        <form method="post" id="order-review-form" action="<?= $escaper->escapeUrl($block->getPlaceOrderUrl()) ?>"
            class="form order-review-form">
            <?= $block->getChildHtml('agreements') ?>
            <div class="actions-toolbar" id="review-buttons-container">
                <div class="primary">
                    <button type="button" id="review-button" class="action checkout primary"
                            value="<?= $escaper->escapeHtml(__('Place Order')) ?>">
                        <span><?= $escaper->escapeHtml(__('Place Order')) ?></span>
                    </button>
                </div>
                <span class="please-wait load indicator" id="review-please-wait"
                    data-text="<?= $escaper->escapeHtml(__('Submitting order information...')) ?>">
                <span><?= $escaper->escapeHtml(__('Submitting order information...')) ?></span>
                </span>
                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'span#review-please-wait') ?>
            </div>
        </form>
    </div>
    <div class="paypal-review-sidebar">
        <button class="cart-sidebar-close" type="button">
                <span>Close</span>
            </button>
        <div class="paypal-review-items">
            <div class="paypal-review-title">
                <strong><?= $escaper->escapeHtml(__('Order Summary')) ?></strong>
            </div>
            <?= $block->getChildHtml('details') ?>

        </div>
        <div class="paypal-review-discount">
            <?= $block->getChildHtml('paypal.additional.actions') ?>
        </div>
    </div>
</div>

<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
<script type="text/x-magento-init">
    {
        "#order-review-form": {
            "validation": {},
            "orderReview": {
                "shippingSubmitFormSelector": "#shipping-method-form",
                "shippingSelector": "#shipping-method",
                "shippingMethodUpdateUrl": "<?= $escaper->escapeJs($block->getUpdateShippingMethodsUrl()) ?>",
                "isAjax": <?= /* @noEscape */ $block->getUseAjax() ? 'true' : 'false' ?>,
                "canEditShippingMethod": <?= /* @noEscape */ $block->canEditShippingMethod() ? 'true' : 'false' ?>
            }
        }
    }
</script>
<script>
    require(['jquery'], function ($) {
        $( ".show-cart-btn" ).click(function() {
            $(".paypal-review-sidebar").addClass('open-sidebar')
        });
        $( ".cart-sidebar-close" ).click(function() {
            $(".paypal-review-sidebar").removeClass('open-sidebar')
        });
    });
</script>