<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Magewire\Checkout\TermsConditions;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var TermsConditions $magewire */

$availableTerms = $magewire->getAgreements();
$viewType = $magewire->getSystemConfig()->getTermsAndConditionsType();
?>
<div>
    <?= $block->getChildBlock($viewType)->setData([
        'terms' => $availableTerms
    ])->toHtml() ?>
</div>
