<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Hyva\Theme\ViewModel\StoreConfig $storeConfig */
$storeConfig = $viewModels->require(Hyva\Theme\ViewModel\StoreConfig::class);
$showMiniCart = $storeConfig->getStoreConfig(\Magento\Checkout\Block\Cart\Sidebar::XML_PATH_CHECKOUT_SIDEBAR_DISPLAY);
?>
<script>
    function initHeader () {
        return {
            searchOpen: false,
            cart: {},
            getData(data) {
                if (data.cart) { this.cart = data.cart }
            }
        }
    }
    function initCompareHeader() {
        return {
            compareProducts: null,
            itemCount: 0,
            receiveCompareData(data) {
                if (data['compare-products']) {
                    this.compareProducts = data['compare-products'];
                    this.itemCount = this.compareProducts.count;
                }
            }
        }
    }
</script>
<div id="header"
     class="relative z-[9999] w-full bg-container-lighter sticky"
     x-data="initHeader()"
     @keydown.window.escape="searchOpen = false;"
     @private-content-loaded.window="getData(event.detail.data)"
>
    <div class="relative container p-0 lg:max-w-full">
        <div class="container flex flex-wrap items-center justify-between w-full px-6 py-4 mx-auto mt-0 relative">
            <!--Logo-->
            <?= $block->getChildHtml('logo'); ?>

            <!--Search-->
            <div class="flex items-center order-3 w-full mt-3 lg:mt-0 lg:w-6/12 lg:order-2" id="search-content" x-show="true">
                <?= $block->getChildHtml('header-search'); ?>
            </div>

            <div class="flex items-center order-2 items-end justify-end lg:order-3 lg:w-4/12">
                <div class="contact hidden lg:block">
                    <a href="#">
                        <?= $heroicons->phoneHtml("inline-block w-8 h-8 text-[#126366] md:h-6 md:w-6 hover:text-black", 25, 25) ?>
                        <p class="inline-block font-sans text-sm font-medium text-black leading-5 m-0">Call Us: 0330 057 7142</p>
                    </a>
                </div>
                <!--Cart Icon-->
                <a id="menu-cart-icon"
                   <?php if ($showMiniCart): ?>@click.prevent.stop="$dispatch('toggle-cart',{});"<?php endif ?>
                   class="relative inline-block ml-1 no-underline items-center justify-center sm:ml-3 lg:ml-10 hover:text-black"
                   href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>"
                >
                    <?= $heroicons->shoppingCartHtml("w-5 h-5 mx-auto mb-0.5 text-[#126366] md:h-6 md:w-6 hover:text-black", 25, 25) ?>
                    <span class="label font-sans font-medium text-sm leading-5">
                    <?= $escaper->escapeHtml(__('Basket')) ?>
                </span>
                    <span x-text="cart.summary_count"
                          class="absolute top-0 right-0 hidden h-5 px-2 py-1 -mt-5 -mr-4 text-xs font-semibold
                        leading-none text-center text-white uppercase transform -translate-x-1
                        translate-y-1/2 rounded-full bg-primary"
                          :class="{
                        'hidden': !cart.summary_count,
                        'block': cart.summary_count }"
                    ></span>
                </a>
                <!--Customer Icon & Dropdown-->
                <?= $block->getChildHtml('customer') ?>
            </div>
        </div>
        <div class="container flex flex-wrap items-center justify-center w-full px-6 mx-auto mt-0">
            <!--Main Navigation-->
            <?= $block->getChildHtml('topmenu') ?>
        </div>
    </div>

    <!--Cart Drawer-->
    <?= $block->getChildHtml('cart-drawer'); ?>

    <!--Authentication Pop-Up-->
    <?= $block->getChildHtml('authentication-popup'); ?>
</div>

