<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Customer\Block\Form\Login\Info;
use Magento\Framework\Escaper;

/** @var Info $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="block-existing-customer w-full">
        <p><?= $escaper->escapeHtml(__('Already have an account?')) ?> <a href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>" class=""><span><?= $escaper->escapeHtml(__('Sign In')) ?></span></a></p>
    </div>
<?php endif; ?>