<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \Magento\Backend\Block\Store\Switcher\Form\Renderer\Fieldset $block */
?>
<?php
/** @var \Magento\Framework\Data\Form\Element\Fieldset $element */
$element = $block->getElement();
$elementFieldContainerId = $element->getFieldsetContainerId();
if ($elementFieldContainerId): ?>
<div id="<?= /** @noEscape */ $elementFieldContainerId ?>">
    <?php endif; ?>
    <?php if (!$element->getNoContainer()): ?>
    <fieldset class="admin__fieldset fieldset <?= $block->escapeHtmlAttr($element->getClass()) ?>"
              id="<?= /** @noEscape */ $element->getHtmlId() ?>">
        <?php endif; ?>
        <?php $legend = $element->getLegend(); ?>
        <?php if ($legend): ?>
            <legend class="admin__legend legend">
                <span><?= $block->escapeHtml($legend) ?></span>
            </legend><br/>
            <?= /** @noEscape */ $element->getHeaderBar() ?>
        <?php else: ?>
            <?= /** @noEscape */ $block->getHintHtml() ?>
        <?php endif; ?>
        <div class="admin__fieldset tree-store-scope">
            <?php $comment = $element->getComment(); ?>
            <?php if ($comment): ?>
                <p class="comment"><?= $block->escapeHtml($comment) ?></p>
            <?php endif; ?>
            <?php
            if ($element->hasHtmlContent()):
                echo /** @noEscape */ $element->getHtmlContent();
            else:
                foreach ($element->getChildren() as $firstChild) {
                    echo /** @noEscape */ '<span class="' . $block->escapeHtmlAttr($firstChild->getData('class'))
                        . ' store-switcher-container ">';
                    echo /** @noEscape */ $firstChild->getHtml();
                    echo /** @noEscape */ '</span>';
                }
            endif;
            ?>
        </div>
        <?= /** @noEscape */ $element->getSubFieldsetHtml() ?>
        <?php if (!$element->getNoContainer()): ?>
    </fieldset>
<?php endif; ?>
    <?php if ($elementFieldContainerId): ?>
</div>
<?php endif; ?>
