<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityFormElementInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var EntityFormElementInterface $element */
/** @var HeroiconsOutline $iconsViewModel */
/** @var Escaper $escaper */

$iconsViewModel = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsSolid::class);

$element = $block->getData('element');
$element->setAttribute('x-bind:type', 'showAsText ? \'text\' : \'password\'')
?>
<div x-data="{ showAsText: false }"
     class="flex items-center gap-4"
>
    <?php /* Re-renders the form element, updating its appearance by switching to a different template. */ ?>
    <?= /* @noEscape */ $element->getRenderer()->renderWithTemplate('Hyva_Checkout::form/field/text.phtml', $element) ?>

    <button type="button"
            x-on:click="showAsText = ! showAsText"
            x-bind:aria-pressed="showAsText"
            x-bind:aria-label="showAsText
                ? '<?= $escaper->escapeJs(__('Hide Password')) ?>'
                : '<?= $escaper->escapeJs(__('Show Password')) ?>'"
    >
        <template x-if="! showAsText">
            <?= $iconsViewModel->eyeHtml('w-6 h-6 mt-1 mx-1') ?>
        </template>

        <template x-if="showAsText">
            <?= $iconsViewModel->eyeOffHtml('w-6 h-6 mt-1 mx-1') ?>
        </template>
    </button>
</div>
