<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityFieldInterface;
use Hyva\Checkout\ViewModel\Form\Field\Street as StreetFormFieldViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\Component\Form as MagewireFormComponent;

/** @var Template $block */
/** @var EntityFieldInterface $element */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var MagewireFormComponent $magewire */

/** @Tailwind md:w-1/4 md:w-2/4 md:w-3/4 md:w-4/4 mb-2 */

$streetFormFieldViewModel = $viewModels->require(StreetFormFieldViewModel::class);
$element = $block->getData('element');
$attributes = $element->getAttributes();
?>
<?php if ($element->hasRelatives()): ?>
    <?php if ($streetFormFieldViewModel->showAsTwoColumnGrid()): ?>
        <div class="grid grid-cols-2 gap-y-2 gap-x-4 place-items-end">
    <?php elseif ($streetFormFieldViewModel->showAsOneColumnRow()): ?>
        <div class="flex flex-row gap-4">
    <?php endif ?>
<?php endif ?>

<div class="w-full font-medium text-gray-700 <?= /* @noEscape */ $element->isRequired() ? 'required' : 'not-required' ?>">
    <?= /* @noEscape */ $element->getRenderer()->renderLabel($element) ?>
    <?= /* @noEscape */ $element->getRenderer()->renderBefore($element) ?>

    <div class="flex items-center gap-4">
        <input class="<?= $escaper->escapeHtmlAttr($element->renderClass(['block w-full form-input grow renderer-text-grid'])) ?>"
            <?php if ($element->hasAttributes()): ?>
                <?= /* @noEscape */ $element->renderAttributes($escaper) ?>
            <?php endif ?>
        />

        <?php if ($element->hasTooltip()): ?>
            <?= /* @noEscape */ $element->getRenderer()->renderTooltip($element) ?>
        <?php endif ?>
    </div>

    <?= /* @noEscape */ $element->getRenderer()->renderAfter($element) ?>
</div>

<?php if ($element->hasRelatives()): ?>
    <?php foreach ($element->getRelatives() as $relative): ?>
        <?php if ($relative->isVisible()): ?>
            <?= /* @noEscape */ $relative->render() ?>
        <?php endif ?>
    <?php endforeach ?>

    </div>
<?php endif ?>

