<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityFormElementInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var EntityFormElementInterface $element */
/** @var Escaper $escaper */

$element = $block->getData('element');
?>
<button class="<?= $escaper->escapeHtmlAttr($element->renderClass(['btn btn-primary'])) ?>"
    <?php if ($element->hasAttributes()): ?>
        <?= /* @noEscape */ $element->renderAttributes($escaper) ?>
    <?php endif ?>
>
    <?= $escaper->escapeHtml(__($element->getLabel())) ?>
</button>
