<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header\Logo;
use Hyva\Theme\ViewModel\Logo\LogoSizeResolver;

/** @var Logo $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var LogoSizeResolver $logoSizeResolver */

/**
 * Unused template, keep for backward compatibility in case it was explicitly referenced by an existing checkout implementation.
 *
 * @deprecated This template is deprecated in favor of the hyva-default theme Magento_Theme/templates/html/header/logo.phtml
 */

$storeName = $block->getThemeName() ?: $block->getLogoAlt();

$logoSizeResolver = $viewModels->require(LogoSizeResolver::class);
$logoWidth = $logoSizeResolver && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();

$logoWidth = $block->getLogoWidth();
$logoHeight = $block->getLogoHeight();

/** @var \Hyva\Theme\ViewModel\Logo\LogoPathResolver $logoPathResolver */
$logoPathResolver = $block->getData('logoPathResolver');
$logoSrc = $logoPathResolver && method_exists($logoPathResolver, 'getLogoSrc')
    ? $logoPathResolver->getLogoSrc($block->getData('logo_file'))
    : $block->getLogoSrc();
?>
<a class="flex items-center justify-between text-xl font-medium tracking-wide text-gray-800
    no-underline hover:no-underline font-title max767:w-[160px]"
   href="<?= $escaper->escapeUrl($block->getUrl('')) ?>"
   title="<?= $escaper->escapeHtmlAttr($storeName) ?>"
   aria-label="store logo">
    <img src="<?= $escaper->escapeUrl($logoSrc) ?>"
         title="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
        <?= $logoWidth ?
            'width="' . $escaper->escapeHtmlAttr($logoWidth) . '"' :
            'width="200"' ?>
        <?= $logoHeight ?
            'height="' . $escaper->escapeHtmlAttr($logoHeight) . '"' :
            'height="150"' ?>
    />
</a>
