<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ProductPage $productViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\SvgIcons;

$productViewModel = $viewModels->require(ProductPage::class);
$product = $productViewModel->getProduct();
$heroicons = $viewModels->require(HeroiconsOutline::class);
$hyvaicons = $viewModels->require(SvgIcons::class);

?>
<h2 class="w-full">
    <button @click="expanded = ! expanded" class="flex items-center justify-between w-full text-left text-lg md:text-2xl leading-6 font-medium font-serif lg:leading-8 text-[#1D3654]"><?= $escaper->escapeHtml(__('Description')) ?> <?= $heroicons->chevronDownHtml('inline-block float-right w-10 h-6 text-[#126366] transition-transform transform duration-300 ease-in-out', 32,16,[":class" => "{ 'rotate-180': expanded }"]); ?></button>
    
</h2>
