<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Name;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\ReCaptcha;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */
/** @var ReCaptcha|null $recaptcha */

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<form class="form form-edit-account lg:grid lg:grid-cols-2 lg:gap-x-6"
      action="<?= $escaper->escapeUrl($block->getUrl('customer/account/editPost')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      x-data="initForm()"
      @submit.prevent="submitForm()"
      autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend font-serif text-xl leading-7 font-normal pb-2 border-b border-gray-200 mb-6 lg:text-2xl lg:leading-10 block-title w-full"><span><?= $escaper->escapeHtml(__('Account Information')) ?></span></legend>
        <br>
        <?= $block->getLayout()->createBlock(Name::class)->setObject($block->getCustomer())->toHtml() ?>
        <?php $dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php $gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($dob->isEnabled()): ?>
            <?= $dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($taxvat->isEnabled()): ?>
            <?= $taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($gender->isEnabled()): ?>
            <?= $gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>

        <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" value="1"
                   title="<?= $escaper->escapeHtmlAttr(__('Change Email')) ?>"
                   x-on:change="showEmailField = !showEmailField"
                   class="checkbox"/>
            <label class="label" for="change-email">
                <span><?= $escaper->escapeHtml(__('Change Email')) ?></span>
            </label>
        </div>

        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" value="1"
                   title="<?= $escaper->escapeHtmlAttr(__('Change Password')) ?>"
                   x-on:change="showPasswordFields = !showPasswordFields"
                <?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?>
                   class="checkbox"/>
            <label class="label" for="change-password">
                <span><?= $escaper->escapeHtml(__('Change Password')) ?></span>
            </label>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
        <?= $recaptcha ? $recaptcha->getInputHtml('customer_edit') : '' ?>
    </fieldset>
    <fieldset class="fieldset info mt-0">
        <template x-if="showEmailField || showPasswordFields">
            <legend class="legend font-serif text-xl leading-7 font-normal pb-2 border-b border-gray-200 mb-6 lg:text-2xl lg:leading-10 block-title w-full"><span><?= $escaper->escapeHtml(__('Change Details')) ?></span></legend>
            <div class="field password current required">
                <label class="label" for="current-password">
                    <span><?= $escaper->escapeHtml(__('Current Password')) ?></span>
                </label>
                <div class="control">
                    <input type="password" class="form-input" name="current_password" id="current-password" data-input="current-password" autocomplete="off"/>
                </div>
            </div>
        </template>
        <template x-if="showPasswordFields">
            <div>
                <div class="field">
                    <label class="label" for="password"><span>
                            <?= $escaper->escapeHtml(__('New Password')) ?>
                    </span></label>
                    <div class="control">
                        <?php $minimumPasswordLength = $block->getMinimumPasswordLength() ?>
                        <input type="password" class="form-input" name="password" id="password" required
                               x-on:change="checkPasswordsMatch()"
                               minlength="<?= $escaper->escapeHtmlAttr($minimumPasswordLength) ?>" autocomplete="off"/>
                    </div>
                    <p class="text-sm text-secondary mt-3">
                        <?= $escaper->escapeHtml(
                            __(
                                'Minimum of different classes of characters in password is %1. Classes of characters: Lower Case, Upper Case, Digits, Special Characters.',
                                $block->getRequiredCharacterClassesNumber()
                            )
                        ) ?>
                    </p>
                </div>
                <div class="field">
                    <label class="label" for="password-confirmation">
                        <span><?= $escaper->escapeHtml(__('Confirm New Password')) ?></span>
                    </label>
                    <div class="control">
                        <input type="password" class="form-input" name="password_confirmation"
                               id="password-confirmation"
                               x-on:change="checkPasswordsMatch()"
                               autocomplete="off"/>
                    </div>
                </div>

                <p class="my-4 text-red"
                   :class="passwordsMatching ? 'invisible' : 'visible'"
                >
                    <?= $escaper->escapeHtml(__('Your password confirmation must match your password.')) ?>
                </p>
            </div>
        </template>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $escaper->escapeHtmlAttr(__('Save Changes')) ?>">
                <span><?= $escaper->escapeHtml(__('Save Changes')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<div class="w-full">
    <?= $recaptcha ? $recaptcha->getLegalNoticeHtml('customer_edit') : '' ?>
</div>
<script>
    function initForm() {
        return {
            errors: 0,
            hasCaptchaToken: 0,
            displayErrorMessage: false,
            errorMessages: [],
            passwordsMatching: true,
            showEmailField: false,
            showPasswordFields: <?= $block->getChangePassword()
                ? $escaper->escapeJs('true')
                : $escaper->escapeJs(
                    'false'
                ) ?>,
            checkPasswordsMatch() {
                if (!this.showPasswordFields) {
                    return true;
                }
                if (document.getElementById('password').value ===
                    document.getElementById('password-confirmation').value) {
                    this.passwordsMatching = true;
                    return true;
                }
                this.passwordsMatching = false;
                return false;
            },
            setErrorMessages(messages) {
                this.errorMessages = [messages]
                this.displayErrorMessage = this.errorMessages.length
            },
            submitForm() {
                if (!this.checkPasswordsMatch()) {
                    return;
                }
                // Do not rename $form, the variable is expected to be declared in the recaptcha output
                const $form = document.querySelector('#form-validate');
                <?= $recaptcha ? $recaptcha->getValidationJsHtml('customer_edit') : '' ?>

                if (this.errors === 0) {
                    $form.submit();
                }
            }
        }
    }
</script>
