<script defer src="<?= $block->getViewFileUrl('Klevu_Search::js/klevu_reliant.js') ?>"></script>
<?php
    /** @var Klevu\Search\Block\Search\Index\ThemeV2 $block */
    $contentMinHeight = $block->getContentMinHeight();
?>
<?php if ($contentMinHeight): ?>
    <style>.klevuLanding { min-height: <?php /** @noEscape */ echo $contentMinHeight; ?>px; }</style>
<?php endif; ?>
<div class="klevuLanding"></div>
