<?php
declare(strict_types=1);
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_HyvaCompatBase
 * @author     Extension Team
 * @copyright  Copyright (c) 2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CustomerRegistration;
use Magento\Customer\Block\Account\Customer;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Customer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var CustomerRegistration $customerRegistration */
$customerRegistration = $viewModels->require(CustomerRegistration::class);
/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div x-data="{ open: false }" class="relative inline-block ml-3">
    <a
        href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getUrl('customer/account'))) ?>"
        id="customer-menu"
        class="block hover:text-black"
        @click.prevent="open = true"
        :aria-expanded="open ? 'true' : 'false'"
        aria-label="<?= $escaper->escapeHtmlAttr(__('My Account')) ?>"
    >
        <?= $heroicons->userHtml('w-5 h-5 mx-auto mb-0.5 text-[#126366] md:h-6 md:w-6', 25, 25, ['aria-hidden' => 'true']); ?>
        <span class="label font-sans font-medium text-sm leading-5">
            <?= $escaper->escapeHtml(__('Account')) ?>
        </span>
    </a>
    <nav class="absolute right-0 z-20 hidden w-40 py-2 mt-2 -mr-4 px-1 overflow-auto origin-top-right rounded-sm
        shadow-lg sm:w-48 lg:mt-3 bg-container-lighter z-[99]"
         :class="{ 'hidden' : !open }"
         @click.away="open = false"
         aria-labelledby="customer-menu"
    >
        <?php if ($block->customerLoggedIn()): ?>
            <?= $block->getChildHtml('customer_logged-menu') ?>
        <?php else: ?>
            <?= $block->getChildHtml('customer_not-login-menu') ?>
        <?php endif; ?>
    </nav>
</div>
