<?php
declare(strict_types=1);

/**
 * @var $block \Mirasvit\Brand\Block\BrandList
 */
?>
<?php
$collection = $block->getBrandsByLetters();
?>
<div class="mst-brand__brand-list">
    <div class="letter-row js-brand-row grid grid-cols-2 gap-6 md:grid-cols-3 md:gap-8 lg:grid-cols-4 lg:gap-12">
        <?php foreach ($collection as $letter => $brands): ?>
                <?php /** @var \Mirasvit\Brand\Api\Data\BrandInterface $brand */ ?>
                <?php foreach ($brands as $brand): ?>
                    <div class="flex w-full">
                        <div class="flex w-full h-full items-center flex-col text-center bg-[#F2F6FA] rounded-md content-center justify-center py-5 px-5 md:py-6 md:px-6 lg:py-8 lg:px-8 lg:min-h-[230px]">
                            <?php if ($block->canShowImage($brand)): ?>
                                <a href="<?= $brand->getUrl() ?>">
                                    <img alt="<?=$brand->getLabel() ?>" src="<?= $brand->getImage() ?>">
                                </a>
                            <?php endif; ?>
                            <h3 class="font-sans text-lg leading-7 font-bold md:text-2xl md:leading-9 lg:font-serif text-[#1D3654]"><a href="<?= $brand->getUrl() ?>"><?= $brand->getLabel() ?></a></h3>
                        </div>
                    </div>
                <?php endforeach; ?>
        <?php endforeach; ?>
    </div>
</div>