<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<div class="column column-main space-y-6">
    <?= $block->getChildHtml('column.main') ?>
    <?= $block->getChildHtml('hyva.checkout.navigation') ?>
</div>
