<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<div class="flex flex-col lg:flex-row pb-[50px] gap-5">
    <div class="column column-main w-full lg:w-[890px] lg:pr-0 checkout-left max767:order-2">
        <?= $block->getChildHtml('column.main') ?>
    </div>

    <div class="realtive column column-right w-full lg:w-[495px] ml-auto lg:pl-0 checkout-sidebar" x-data="initializeOrderSummaryToggle()" :class="{ 'active': isActive }">
        <div class="column-right-wrap sticky top-0" @scroll.window="updateToggle()">
            <div class="md:hidden flex items-center justify-between border-t border-b border-[#000000] bg-[#F5F5F5] mx-[-15px] py-[10px] px-5" @click="isActive = !isActive">
                <div class="flex items-center text-[#000000] text-lg">
                    <svg class="mr-2.5" width="27" height="24" viewBox="0 0 27 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M10.6529 22.7192C11.3193 22.7192 11.8595 22.179 11.8595 21.5126C11.8595 20.8462 11.3193 20.306 10.6529 20.306C9.98651 20.306 9.44629 20.8462 9.44629 21.5126C9.44629 22.179 9.98651 22.7192 10.6529 22.7192Z" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M20.3059 22.7192C20.9723 22.7192 21.5125 22.179 21.5125 21.5126C21.5125 20.8462 20.9723 20.306 20.3059 20.306C19.6395 20.306 19.0993 20.8462 19.0993 21.5126C19.0993 22.179 19.6395 22.7192 20.3059 22.7192Z" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M1 1H5.22317C5.22317 1 5.72144 3.20622 6.0407 4.61986C6.67863 7.44455 7.55479 11.3241 8.06882 13.6001C8.31731 14.7003 9.29429 15.4795 10.4223 15.4795H20.7834C21.9145 15.4795 22.8938 14.6938 23.1391 13.5898L25.1324 4.61986" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        <path d="M25.1324 4.61987H6.42981" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <?= __('Show Order Details');?>
                    <span class="mobile-arrow ml-2 -mt-1 border-[#000000] border-b-[3px] border-r-[3px] w-3 h-3 transform rotate-45" :class="{ '!mt-2.5 rotate-[225deg] active': isActive }"></span>
                </div>
                <span class="leading-8 text-xl text-[#000000] font-bold summary-price-holder">Price</span>
            </div>
            <?= $block->getChildHtml('column.right') ?>
        </div>
    </div>
</div>
<script>
    function initializeOrderSummaryToggle () {
        return {
            isActive: false,
            updateToggle: function () {
                if (window.pageYOffset >= 130 && this.isActive === true) {
                    this.isActive = false;
                }
            }
        }
    }
    window.addEventListener('scroll', function() {
        if (window.scrollY >= 180) {
            document.body.classList.add('scrolled');
        } else {
            document.body.classList.remove('scrolled');
        }
    });
</script>
